<div class="convert-wrapper three">
    <div class="method-title">Payoneer Account</div>
    <div class="steps">
        <ul class="progressbar">
            <li class="active"> Lörem ipsumbr <br> menskopp dedobel</li>
            <li >Lörem ipsumbr <br> menskopp dedobel</li>
            <li >Lörem ipsumbr <br> menskopp dedobel</li>
        </ul>
    </div>
    <div class="support-wrapper"><p class="needsupport">Need assistance?</p> <img src="/assets/images/test.svg" alt="">
        <p class="needsupport ml-8">Contact support</p></div>
    <div class="timeline">
        <div class="outer">

            <div class="card">
                <div class="timeline-indi"></div>
                <div class="info-payment-method">
                    <h3 class="title-convert">Confirm order info</h3>
                    <div class="convert-order-info-data">
                        <div class="data-wrapper">
                            <p class="info-title-convert">Amount</p>
                            <p class="info-amount">$ 30</p>
                        </div>
                        <div class="data-wrapper">
                            <p class="info-title-convert">Total Value</p>
                            <p class="info-amount value-col">N 17,250</p>
                        </div>
                        <div class="data-wrapper">
                            <p class="info-title-convert">Status</p>
                            <p class="info-amount status-col">In progress</p>
                        </div>
                        <div class="data-wrapper">
                            <p class="info-title-convert">Duration</p>
                            <p class="info-amount">12:05</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="timeline-indi"></div>

                <div class="info-payment-method">
                    <h3 class="title-convert">Transfer funds to account provided below <span><img
                                    src="/assets/images/i.svg" alt=""></span></h3>
                    <div class="fund-acc-info">
                        <p class="acc-title">Beneficiary Name /</p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">Brace Network LLC</p>
                            <div class="verified">
                                <div class="verified-text">Verified</div>
                                <span><img src="/assets/images/verified.svg" alt=""></span></div>
                        </div>
                    </div>
                    <div class="fund-acc-info">
                        <p class="acc-title">Bank name</p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">Evolve Bank & Trust</p>
                            <div class="copy-wrapper">
                                <img src="/assets/images/copy.svg" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="fund-acc-info">
                        <p class="acc-title">Account Number </p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">9800605135</p>
                            <div class="copy-wrapper">
                                <img src="/assets/images/copy.svg" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="fund-acc-info">
                        <p class="acc-title">ABA Routing Number</p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">084106768</p>
                            <div class="copy-wrapper">
                                <img src="/assets/images/copy.svg" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="fund-acc-info">
                        <p class="acc-title">Bank Address</p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">6070 Poplar Ave, Suite 200 Memphis, TN 38119</p>
                            <div class="copy-wrapper">
                                <img src="/assets/images/copy.svg" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="fund-acc-info">
                        <p class="acc-title">Type of Account</p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">Checking</p>
                            <div class="copy-wrapper">
                                <img src="/assets/images/copy.svg" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="fund-acc-info">
                        <p class="acc-title">Beneficiary Address</p>
                        <div class="info-acc-fund-wrapper">
                            <p class="name-fund">1309 Coffeen Avenue, Ste 1200 Sheridan, WY 82801</p>
                            <div class="copy-wrapper">
                                <img src="/assets/images/copy.svg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="timeline-indi"></div>

                <div class="info-payment-method">
                    <h3 class="title-convert">After transferring the funds, click on “Transferred, notify us”
                        button <span><img
                                    src="/assets/images/i.svg" alt=""></span></h3>
                    <div class="gateway-btn-wrapper">
                        <div class="notify">Transferred, notify us</div>
                        <div class="notify cancel-order">Cancel Order</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--<div class="btn-wrapper-choice">
        <button class="btn-cancel m0 m40" id="back_to_two">Cancel</button>
        <button class="btn-continue m0 m40" id="third_sec">Continue</button>
    </div>-->
</div>