<?php if ($transactions!='') { ?>
    <tr class="bl">
        <th class="bl">Fund Conversion</th>
        <td class="bl">01 Apr 2022</td>
        <td class="bl">N 17,250</td>
        <td class="bl"><span class="successful">Successful</span></td>
        <!-- <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">--:--</span></td> -->
    </tr>
<?php } else { ?>
    <tr>
        <td colspan="9" class="text-center">No data found</td>
    </tr>
<?php } ?>
