<section class="hero-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 hero-content">
                    <h2 class="hero-heading">You launch your business. <br> We’ll handle the paperwork</h2>
                    <p class="hero-description">It's one simple platform for Currency exchange, Foreign Account, Sell
                        digital service or product Internationally, Micro Business Account, Micro Business POS and much
                        more.</p>

                    <div class="join-ceda">
                        <a href="/register" class="btn btn-get-start-cta">Launch My Company</a>
                    </div>

              
            </div>
            <div class="col-lg-6">
                    <img class="side-img" src="./assets/images/bus-side-img.png" alt="CEDA Banner">
                
            </div>
        </div>
    </div>
</section>



<!------------Convert Section------------->

<section class="convert convert-up-bus">

    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="convert-1">
                    <img src="./assets/images/bus-icon1.png" class="convert-img" alt="">
                    <div class="convert-header">
                       Business Registration
                    </div>
                    <p class="convert-text">
                        It’s one simple platform for Currency exchange,
                        Foreign Account, Sell digital service or product
                        Internationally, Micro Business Account, Micro Business POS and much more.
                    </p>
                </div>

            </div>
            <div class="col-lg-4">
                <div class="convert-2">
                    <img src="./assets/images/bus-icon2.png" class="convert-img" alt="">
                    <div class="convert-header mt-convert">
                        TIN Number
                    </div>
                    <p class="convert-text">
                        It’s one simple platform for Currency exchange,
                        Foreign Account, Sell digital service or product
                        Internationally, Micro Business Account, Micro Business POS and much more.
                    </p>
                </div>

            </div>
            <div class="col-lg-4">
                <div class="convert-3">
                    <img src="./assets/images/bus-icon3.png" class="convert-img" alt="">
                    <div class="convert-header">
                        Business Account
                    </div>
                    <p class="convert-text">
                        It’s one simple platform for Currency exchange,
                        Foreign Account, Sell digital service or product
                        Internationally, Micro Business Account, Micro Business POS and much more.
                    </p>
                </div>

            </div>
        </div>
    </div>
</section>


<!------------What do you get------------->
<section class="what-you-get">
    <div class="container">
       
       <div class="row">
           <div class="col-lg-6">
               <img src="./assets/images/ipad-pro.png" class="ipad-img" alt="">
           </div>
           <div class="col-lg-6">
                <div class="what-title">
                What do you get?
                </div>

                <p class="what-text">You may be starting a business, or you have one running already. For ₦15,000 you get the following:</p>

                <div class="what-list"><img src="./assets/images/list-mark.png" alt=""> Premium Processing - register in 3 days!</div>
                <div class="what-list"><img src="./assets/images/list-mark.png" alt=""> Free website to sell to more customers</div>
                <div class="what-list"><img src="./assets/images/list-mark.png" alt=""> Instant loans to scale your business</div>
                <div class="what-list"><img src="./assets/images/list-mark.png" alt=""> VIP access to network of 300,000+ merchants</div>

                <a href="/register" class="btn btn-get-start-cta what-btn">Launch My Company</a>
           </div>
       </div>
    </div>

</section>
<!------------Faq section ------------->
<section class="faq-sec">
    <div class="container">
        <div class="faq" id="faq">
        


                <div class="show-faq">
                    <div class="flex q">
                        <p class="faqQues">How long does it take to build a Product ? </p>
                        <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>
                       

                    </div>

                    

                    <div class="faqAns hide">
                        <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                        </p>
                        </div>

                    </div>
                

                </div>
                <div class="show-faq">
                    <div class="flex q">
                        <p class="faqQues">How long does it take to build a Product ? </p>
                        <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>
                       

                    </div>


                    
                    <div class="faqAns hide">
                        <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                        </p>
                        </div>

                </div>
                <div class="show-faq">
                    <div class="flex q">
                        <p class="faqQues">How long does it take to build a Product ? </p>
                        <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>
                       

                    </div>


                    
                    <div class="faqAns hide">
                        <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                        </p>
                        </div>

                </div>
                <div class="show-faq">
                    <div class="flex q">
                        <p class="faqQues">How long does it take to build a Product ? </p>
                        <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>
                       

                    </div>


                    
                    <div class="faqAns hide">
                        <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                        </p>
                        </div>

                </div>
                <div class="show-faq">
                    <div class="flex q">
                        <p class="faqQues">How long does it take to build a Product ? </p>
                        <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>
                       

                    </div>


                    
                    <div class="faqAns hide">
                        <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                        </p>
                        </div>

                </div>
                


        </div>

          
        </div>
    </div>

</section>

<script>

function faqControl(){
        $(".faqAns").hide();       
        $(".q").on("click", function() {
           
           if($(this).next(".faqAns").hasClass("active")){
               $(this).next().slideToggle().removeClass("active");
               $(this).children("i").removeClass("fa-minus").addClass("fa-plus")
           }else{
               $(this).next().slideToggle().addClass("active");
               $(this).children("i").removeClass("fa-plus").addClass("fa-minus")

              

              
           }
       });
    }
    $(document).ready(function() {
        faqControl()
      
    });

  

   
</script>
<?php include 'templates/footer.phtml'; ?>