<div class="ceda-wrapper plr" onload="UseEffect()">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right minH col-9-ceda">

                <!-- <div class="border-header"></div> -->
                <div class="content-wrapper">

                    <div class="convert-wrapper one">
                        <div class="convert-dis-wrap">
                            <p class="convert-display mb0">1 <span class="selected_currency">USD</span> ≈ <span class="selected_amount"></span> <?=$_SESSION['currency']?></p> <span><img src="../assets/images/rotated-convert.svg" alt=""></span>
                        </div>
                        <div class="amount-to-convert">
                            <p class="title">Amount to convert</p>
                            <div class="convert-from-rate">
                                <!--<div class="price-from-convert">30</div>-->
                                <input type="number" class="price-from" id="entered_currency" value="<?= $amount ?>">

                                <select name="countries" id="price_to" class="price_to-convert">
                                    <?php foreach ($exchange_rates as $exchange_rate) { ?>
                                        <option value="<?= $exchange_rate['ceda_rate'] ?>">
                                            <?= $exchange_rate['currency_from_sign'] ?> <?= $exchange_rate['currency_from'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="amount-to-convert toggle1 mb0">
                            <p class="title">Equivalent Value</p>
                            <div class="convert-from-rate">
                                <!-- <div class="price-from-convert">17,250</div>-->
                                <div class="price-from no-border"
                                     id="converted_price"><?= number_format($equivalent) ?></div>
                                <div class="price_to-convert" id="price_to"><span><img
                                                src="/assets/images/<?= $_SESSION['iso'] ?>.svg"
                                                alt=""
                                                class="converted_to_img"></span><span class="capita"><?= $_SESSION['currency'] ?></span>
                                </div>
                            </div>
                        </div>
                        <p class="title-res-amount">Select Residing Account / Payment Method </p>

                        <select class="method" name="residing_method" id="residing_method" >
                            <option value="">Select Payment Method</option>
                            <option value="payoneer">Pay with Payoneer Fund</option>
                            <option value="wise fund">Pay with Wise Fund</option>
                            <option value="us bank">Pay with US Bank Transfer</option>
                            <option value="bank">Pay with Local Bank Transfer</option>
                            <option value="card">Pay with Card</option>

                        </select>

                        <p class="title-res-amount">Select Recipient Details</p>

                        <select class="method" name="choose_NGN" id="choose_NGN" onChange="handlechange()">
                            <option value="">Select Recipients Details</option>
                            <option value="account details">0002222111 - Access bank</option>
                            <option value="add" > Add New Recipient </option>
                        </select>

                        <div class="mt-10" >

                            <span class="ceda-charge">Ceda Charge: 1% | Payment Charge 3%</span>
                            <div class="value-after">Value After Charges: <br>
                                <span>15,250 NGN</span></div>
                        </div>

                        <button class="btn-submit m0 m40" id="first_sec">Continue Transaction</button>

                        <div id="myModal" class="mymodal">

                            <!-- Modal content -->
                            <div class="close-modal"> <span>&times;</span> </div>
                            <div class="modal-content">

                                <div class="modal_head">

                                    <div class="modal-heading">Add a Recipient</div>

                                    <div class="modal-text">Kindly enter your recipient's bank details below</div>

                                </div>

                                <div class="modal_body">

                                    <p class="title-input">Bank Account Number </p>

                                    <input type="number" PLACEHOLDER="Enter Bank Account Number" class="account-no">

                                    <p class="title-input">Recipient Bank Name  </p>

                                    <select class="method" name="recipient-bank-name" id="recipient-bank-name" >
                                        <option value="">-- Select Recipient account bank --</option>

                                    </select>

                                    <button class="btn-submit m0 m40" id="add-bank-acc">Add Bank Account</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
<?php include 'templates/footer.phtml'; ?>
<script>

    // Get the modal
    let modal = document.getElementById("myModal");

    let span = document.getElementsByClassName("close-modal")[0];

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    const handlechange = ()=>{
        let choose_NGN = document.getElementById("choose_NGN");
        let value = choose_NGN.options[choose_NGN.selectedIndex].value;

        if(value == "add"){
            modal.style.display = "block";


        }
    }
    document.addEventListener("DOMContentLoaded", ()=>{
        console.log("its working now")

        fetch('https://nigerianbanks.xyz/')
            .then(response => response.json())
            .then(result => {

                let bankOption = result.map((item,i)=>{
                    return (
                        ` <option value="${item.slug}">${item.name}</option>`
                    )

                })
                document.getElementById("recipient-bank-name").innerHTML= bankOption;
                console.log('Success:', result);
            })
            .catch(error => {
                console.error('Error:', error);
            });

    })
    let exchangeRate = $('#price_to').val();
    let input = $('#entered_currency').val();

    $('.selected_amount').html(exchangeRate)
    $('.selected_currency').html($("#price_to option:selected").text().replace('$ ','').replace('£ ','').replace('€ ',''))

    $('#first_sec').click(function () {
        let res = '<?=$res?>';

        if (res === "0") {
            window.location.href = "/bank-transfer?q=" + $('#residing_method').val +"&am="+ $('#entered_currency').val() + "&eq="+convertCurrency($('#entered_currency').val(), $('#price_to').val());
            return
        }
        if (res === "1") {
            $('#snackbar').html('Your KYC verification under review');
            showToast();
            return
        }
        if (res === "2") {
            $('#snackbar').html('Please enter your KYC information first');
            showToast();
            setTimeout(function () {
                window.location.href = "/kyc-verification";
            }, 5000)

            return
        }
        let sign = $("#price_to option:selected").text().replace(' USD','').replace(' GBP','').replace(' EUR','');
        sign =encode( $.trim(sign))
       window.location.href = "/bank-transfer?q=" + encode( $('#residing_method').val()) +"&am="+encode( $('#entered_currency').val()) + "&eq="+encode(String(convertCurrency($('#entered_currency').val(), $('#price_to').val())))+ '&s='+sign;
    });
    $('#price_to').on('change', function () {
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('.selected_amount').html(exchangeRate)
        $('.selected_currency').html($("#price_to option:selected").text().replace('$ ','').replace('£ ','').replace('€ ',''))


        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })
    $('#entered_currency').keyup(function () {
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })


</script>
