<div class="ceda-wrapper plr">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right minH col-9-ceda">

                <!-- <div class="border-header"></div> -->
                <div class="content-wrapper">

                    <div class="convert-wrapper one">
                        <div class="convert-dis-wrap">
                            <p class="convert-display mb0">1 <span class="selected_currency">USD</span> ≈ <span class="selected_amount"></span> <?=$_SESSION['currency']?></p> <span><img src="../assets/images/rotated-convert.svg" alt=""></span>
                        </div>
                        <div class="amount-to-convert">
                            <p class="title">Amount to convert</p>
                            <div class="convert-from-rate">
                                <!--<div class="price-from-convert">30</div>-->
                                <input type="number" class="price-from" id="entered_currency" value="<?= $amount ?>">

                                <select name="countries" id="price_to" class="price_to-convert">
                                    <?php foreach ($exchange_rates as $exchange_rate) { ?>
                                        <option value="<?= $exchange_rate['ceda_rate'] ?>">
                                            <?= $exchange_rate['currency_from_sign'] ?> <?= $exchange_rate['currency_from'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="amount-to-convert toggle1 mb0">
                            <p class="title">Equivalent Value</p>
                            <div class="convert-from-rate">
                                <!-- <div class="price-from-convert">17,250</div>-->
                                <div class="price-from no-border"
                                     id="converted_price"><?= number_format($equivalent) ?></div>
                                <div class="price_to-convert" id="price_to"><span><img
                                                src="/assets/images/<?= $_SESSION['iso'] ?>.svg"
                                                alt=""
                                                class="converted_to_img"></span><span><?= $_SESSION['currency'] ?></span>
                                </div>
                            </div>
                        </div>
                        <p class="title-res-amount">Select Residing Account For <span class="selected_currency">USD</span></p>

                        <select class="method" name="residing_method" id="residing_method">
                            <option value="payoneer">Payoneer Account</option>
                            <option value="bank">NGN Domiciliary Account</option>
                        </select>
                        <button class="btn-submit m0 m40" id="first_sec">Continue Transaction</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php include 'templates/footer.phtml'; ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    let exchangeRate = $('#price_to').val();
    let input = $('#entered_currency').val();

    $('.selected_amount').html(exchangeRate)
    $('.selected_currency').html($("#price_to option:selected").text().replace('$ ','').replace('£ ','').replace('€ ',''))

    $('#first_sec').click(function () {
        let res = '<?=$res?>';

        if (res === "0") {
            window.location.href = "/bank-transfer?q=" + $('#residing_method').val +"&am="+ $('#entered_currency').val() + "&eq="+convertCurrency($('#entered_currency').val(), $('#price_to').val());
            return
        }
        if (res === "1") {
            $('#snackbar').html('Your KYC verification under review');
            showToast();
            return
        }
        if (res === "2") {
            $('#snackbar').html('Please enter your KYC information first');
            showToast();
            setTimeout(function () {
                window.location.href = "/kyc-verification";
            }, 5000)

            return
        }
        window.location.href = "/bank-transfer?q=" + $('#residing_method').val() +"&am="+ $('#entered_currency').val() + "&eq="+convertCurrency($('#entered_currency').val(), $('#price_to').val());
    });
    $('#price_to').on('change', function () {
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('.selected_amount').html(exchangeRate)
        $('.selected_currency').html($("#price_to option:selected").text().replace('$ ','').replace('£ ','').replace('€ ',''))


        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })
    $('#entered_currency').keyup(function () {
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })


</script>
