<div class="container ceda-wrapper plr">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right col-9-ceda">
                <div class="content-wrapper pt150">
                    <div class="right-header">
                        <h3 class="header-text">
                            Convert to Local Currency
                        </h3>
                    </div>

                </div>
                <div class="border-header"></div>
                <div class="content-wrapper">
                    <div class="convert-wrapper one">
                        <div class="amount-to-convert">
                            <p class="title">Amount to convert</p>
                            <div class="convert-from-rate">
                                <!--<div class="price-from-convert">30</div>-->
                                <input type="number" class="price-from" id="entered_currency" value="<?=$amount?>">

                                <select name="countries" id="price_to" class="price_to">
                                    <?php foreach ($exchange_rates as $exchange_rate) { ?>
                                        <option value="<?=$exchange_rate['ceda_rate']?>">🇺🇸&emsp;<?=$exchange_rate['currency_from']?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="amount-to-convert mb0">
                            <p class="title">Equivalent Value</p>
                            <div class="convert-from-rate">
                               <!-- <div class="price-from-convert">17,250</div>-->
                                <div class="price-from no-border" id="converted_price"><?=number_format($equivalent)?></div>
                                <div class="price_to" id="price_to"><span><img
                                                src="/assets/images/<?= $_SESSION['iso'] ?>.svg"
                                                alt=""
                                                class="converted_to_img"></span><span><?= $_SESSION['currency'] ?></span>
                                </div>
                            </div>
                        </div>
                        <button class="btn-submit m0 m40" id="first_sec">Continue Transaction</button>
                    </div>
                    <div class="convert-wrapper two">
                        <div class="chose">Choose payment method</div>
                        <div class="amount-to-convert">
                            <div class="convert-from-rate">
                                <div class="price-from-convert medium-wrapper"><img src="/assets/images/payoneer.svg"
                                                                                    alt="payoneer">
                                    <p class="payoneer-text">Payoneer</p></div>
                                <div class="checbox-container">
                                    <div class="round">
                                        <input type="checkbox" value="payoneer" class="checkbox-type" id="checkbox" onclick="check(this);"/>
                                        <label for="checkbox"></label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="amount-to-convert mb0">
                            <div class="convert-from-rate">
                                <div class="price-from-convert medium-wrapper"><img
                                            src="/assets/images/buildingbank.svg"
                                            alt="payoneer">
                                    <p class="payoneer-text">NGN DOM ACCOUNT</p></div>

                                <div class="checbox-container">
                                    <div class="round">
                                        <input type="checkbox" value="bank" class="checkbox-type" id="checkbox-bank" onclick="check(this);"/>
                                        <label for="checkbox-bank"></label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-wrapper-choice">
                            <button class="btn-cancel m0 m40" id="back_to_one">Cancel</button>
                            <button class="btn-continue m0 m40" id="second_sec">Continue</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php include 'templates/footer.phtml'; ?>

<script>
    let type = ""

    function check(input) {
        type = input.value;
        let checkboxes = document.getElementsByClassName("checkbox-type");

        for (let i = 0; i < checkboxes.length; i++) {
            //uncheck all
            if (checkboxes[i].checked == true) {
                checkboxes[i].checked = false;
            }
        }

        //set checked of clicked object
        if (input.checked == true) {
            input.checked = false;
        } else {
            input.checked = true;
        }
    }
    $('#first_sec').click(function () {
        $('.one').hide();
        $('.two').show();
    });
    $('#second_sec').click(function () {
        if(type==""){
            $('#snackbar').html('Please select one option');
            showToast();
            return
        }
        window.location.href="/bank-transfer?q="+type
    });
    $('#back_to_one').click(function () {
        $('.one').show();
        $('.two').hide();
    });
    $('#price_to').on('change',function(){
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('#converted_price').html(numberWithCommas(convertCurrency(input,exchangeRate)));
    })
    $('#entered_currency').keyup(function(){
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('#converted_price').html(numberWithCommas(convertCurrency(input,exchangeRate)));
    })
</script>
