<div class="ceda-wrapper plr" onload="UseEffect()">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right minH col-9-ceda">

                <!-- <div class="border-header"></div> -->
                <div class="content-wrapper">

                    <div class="convert-wrapper one">
                        <div class="convert-dis-wrap">
                            <p class="convert-display mb0">1 <span class="selected_currency">USD</span> ≈ <span
                                        class="selected_amount"></span> <?= $_SESSION['currency'] ?></p> <span><img
                                        src="../assets/images/rotated-convert.svg" alt=""></span>
                        </div>
                        <div class="amount-to-convert">
                            <p class="title">Amount to convert</p>
                            <div class="convert-from-rate">
                                <!--<div class="price-from-convert">30</div>-->
                                <input type="number" class="price-from" id="entered_currency" value="<?= $amount ?>">

                                <select name="countries" id="price_to" class="price_to-convert">
                                    <?php foreach ($exchange_rates as $exchange_rate) { ?>
                                        <option value="<?= $exchange_rate['ceda_rate'] ?>">
                                            <?= $exchange_rate['currency_from_sign'] ?> <?= $exchange_rate['currency_from'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="amount-to-convert toggle1 mb0">
                            <p class="title">Equivalent Value</p>
                            <div class="convert-from-rate">
                                <!-- <div class="price-from-convert">17,250</div>-->
                                <div class="price-from no-border"
                                     id="converted_price"><?= number_format($equivalent) ?></div>
                                <div class="price_to-convert" id="price_to"><span><img
                                                src="/assets/images/<?= $_SESSION['iso'] ?>.svg"
                                                alt=""
                                                class="converted_to_img"></span><span
                                            class="capita"><?= $_SESSION['currency'] ?></span>
                                </div>
                            </div>
                        </div>
                        <p class="title-res-amount">Select Residing Account / Payment Method </p>

                        <select class="method" name="residing_method" id="residing_method">
                            <option value="">Select Payment Method</option>
                            <?php foreach ($payment_methods as $payment_method) { ?>
                                <option value="<?= $payment_method['id'] ?>"><?= $payment_method['payment_method'] ?></option>
                            <?php } ?>

                        </select>

                        <!--<p class="title-res-amount">Select Bank You’re Paying From</p>

                        <select class="method" name="select-bank" id="select-bank">

                            <option value="" disabled selected hidden>Select Bank</option>

                        </select>-->
                        <p class="title-res-amount">Select Recipient Details</p>

                        <select class="method" name="choose_NGN" id="choose_NGN" onChange="handlechange()">
                           <!-- <option value="">Select Recipients Details</option>
                            <?php /*foreach ($kyc_info as $key => $value) { */?>
                                <option value="account details"><?/*= $kyc_info[$key]['bank_name'] */?></option>
                            <?php /*} */?>
                            <option value="add"> Add New Recipient</option>-->
                        </select>

                        <div class="mt-10">

                            <span class="ceda-charge">Ceda Charge: 0% | Payment Charge 0%</span>

                            <div class="ceda-flex">

                                <div class="value-after">You will receive: <br>
                                    <span class="actual_amount"> 0 </span><?= " " . $_SESSION['currency'] ?>
                                </div>

                                <div>
                                    <div class="estimated-deli">Estimated Delivery Time</div>
                                    <span class="estimated-time"><img src="/assets/images/Combined-Shape.png"> <span
                                                class="estimate">0hr-0hrs</span></span>
                                </div>
                            </div>

                        </div>

                        <button class="btn-submit m0 m40" id="first_sec">Continue Transaction</button>

                        <div id="myModal" class="mymodal">

                            <!-- Modal content -->
                            <div class="close-modal"><span>&times;</span></div>
                            <div class="modal-content">

                                <div class="modal_head">

                                    <div class="modal-heading">Add a Recipient</div>

                                    <div class="modal-text">Kindly enter your recipient's bank details below</div>

                                </div>

                                <div class="modal_body">

                                    <p class="title-input">Bank Account Number </p>
                                    <form id="kyc_form" method="post" action="/ajax/insert_kyc_data"
                                          enctype="multipart/form-data">
                                        <input type="number" PLACEHOLDER="Enter Bank Account Number" class="account-no" name="account_number">

                                        <p class="title-input">Recipient Bank Name </p>

                                        <select class="method" name="bank_name" id="recipient-bank-name">
                                            <option value="">-- Select Recipient account bank --</option>

                                        </select>

                                        <button  type="submit" class="btn-submit m0 m40" id="add-bank-acc">Add Bank Account</button>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <div id="stripModal" class="mymodal">

                            <!-- Modal content -->
                            <div class="close-modal"><span>&times;</span></div>
                            <div class="modal-content">

                                <div class="modal_head">

                                    <div class="modal-heading">Card Payment</div>

                                    <div class="modal-text">Lörem ipsum prol sant äras. Relig teplat. </div>

                                </div>

                                <div class="modal_body">
                                    <script src="https://js.stripe.com/v3/"></script>
                                    <script src="/assets/js/script.js"></script>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
<?php include 'templates/footer.phtml'; ?>
<script>
    function getBanks() {
        $.ajax({
            url: "/ajax/get_banks",
            data: {},
            method: "POST",
            cache: false,
            dataType: "html"
        }).done(function (data) {
            $("#choose_NGN").html(data);
        });
    }
    getBanks()
    //trigger on load
    let exchangeRate = $('#price_to').val();
    let input = $('#entered_currency').val();
    $('.actual_amount').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    $('.selected_amount').html(exchangeRate)
    $('.selected_currency').html($("#price_to option:selected").text().replace('$ ', '').replace('£ ', '').replace('€ ', ''))
    let totalPercent = 0
    let paymentMethod = <?php echo json_encode($payment_methods); ?>;

    //when residing method is changes
    $('#residing_method').on('change', function () {

        let exchangeRate = $('#price_to').val();

        if ($('#entered_currency').val() !== '') {


            let selectedMethod = paymentMethod.filter(function (item) {
                return item.id === Number($('#residing_method').val());

                // console.log(item.id,$('#residing_method').val());
            })
            selectedMethod = selectedMethod[0];
            totalPercent = Number(selectedMethod.ceda_charge_inpercent) + Number(selectedMethod.payment_charge_inpercent)
            let inputAfterSub = Number($('#entered_currency').val()) - totalPercent;
            let received = convertCurrency(inputAfterSub, exchangeRate);
            $('.actual_amount').html(numberWithCommas(received));
            $('.estimate').html(selectedMethod.estimate_time);
            $('.ceda-charge').html('Ceda Charge: ' + selectedMethod.ceda_charge_inpercent + "% | " + "Payment Charge: " + selectedMethod.payment_charge_inpercent + "%");
        }
    })


    // Get the modal
    let modalStrip = document.getElementById('stripModal')

    let modalD = document.getElementById("myModal");
    let spanD = document.getElementsByClassName("close-modal")[0];
    let spanStrip = document.getElementsByClassName("close-modal")[1];
    spanD.onclick = function () {
        modalD.style.display = "none";
    }
    spanStrip.onclick = function () {
        modalStrip.style.display = "none";
    }
    window.onclick = function (event) {
        if (event.target == modalD) {
            modalD.style.display = "none";
        }
    }
    const handlechange = () => {
        let choose_NGN = document.getElementById("choose_NGN");
        let value = choose_NGN.options[choose_NGN.selectedIndex].value;

        if (value == "add") {
            modalD.style.display = "block";
        }
    }
    //dom content loader
    document.addEventListener("DOMContentLoaded", () => {
        fetch('https://nigerianbanks.xyz/')
            .then(response => response.json())
            .then(result => {

                let bankOption = result.map((item, i) => {
                    return (
                        ` <option value="${item.name}">${item.name}</option>`
                    )

                })
                document.getElementById("recipient-bank-name").innerHTML = bankOption;
                document.getElementById("select-bank").innerHTML = bankOption;
            })
            .catch(error => {
                console.error('Error:', error);
            });
    })


    $('#first_sec').click(function () {
        let res = '<?=$res?>';
        if (res === "1") {
            $('#snackbar').html('Your KYC verification under review');
            showToast();
            return
        }
        if (res === "2") {
            $('#snackbar').html('Please enter your KYC information first');
            showToast();
            setTimeout(function () {
                window.location.href = "/kyc-verification";
            }, 5000)

            return
        }

        if($('#residing_method').val()=== '6'){

            modalStrip.style.display = "block";
            return
        }
        let sign = $("#price_to option:selected").text().replace(' USD', '').replace(' GBP', '').replace(' EUR', '');
        sign = encode($.trim(sign))
        window.location.href = "/bank-transfer?q=" + encode($('#residing_method').val()) + "&am=" + encode($('#entered_currency').val()) + "&eq=" + encode(String(convertCurrency($('#entered_currency').val(), $('#price_to').val()))) + '&s=' + sign;
    });
    $('#price_to').on('change', function () {
        let exchangeRate = $('#price_to').val();
        let input = Number($('#entered_currency').val());
        let inputAfterSub = Number($('#entered_currency').val()) - totalPercent;

        let received = convertCurrency(inputAfterSub, exchangeRate);
        $('.actual_amount').html(numberWithCommas(received));
        $('.selected_amount').html(exchangeRate)
        $('.selected_currency').html($("#price_to option:selected").text().replace('$ ', '').replace('£ ', '').replace('€ ', ''))


        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })
    $('#entered_currency').keyup(function () {
        let exchangeRate = $('#price_to').val();
        let input = Number($('#entered_currency').val());
        let inputAfterSub = Number($('#entered_currency').val()) - totalPercent;
        let received = convertCurrency(inputAfterSub, exchangeRate);
        if (Number($('#entered_currency').val()) > totalPercent) {
            $('.actual_amount').html(numberWithCommas(received));
        }
        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })

    $('#kyc_form').on('submit', function (e) {
        e.preventDefault();
        $(this).ajaxSubmit({
            //	target: '#output',
            dataType: 'json',
            success: showResponse //call function after success
        });
    });
    function showResponse(res){
        if(res.error!=undefined) {
            $('#snackbar').html(res.error);
            showToast();
            return;
        }
        if(res.message!=undefined) {
            $('#snackbar').html(res.message);
            getBanks()
            showToast();
            return;
        }
    }

</script>
