<div class="container ceda-wrapper">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right">
                <div class="content-wrapper">
                    <div class="right-header">
                        <h3 class="header-text">
                            Home
                        </h3>
                    </div>

                </div>
                <div class="border-header"></div>
                <div class="content-wrapper bottom-content">
                    <div class="user-name"><span class="welcome">Welcome,</span> <?= $_SESSION['name'] ?>! 👋🏾</div>
                    <div class="ceda-rate">Ceda Rate</div>
                    <div class="rate-wrapper">
                        <div class="rate-row">
                            <div class="row-item-left">Currency</div>
                            <div class="row-item-right">Rate</div>
                        </div>
                        <div class="rate-row-td bb-dd">
                            <div class="row-item-left-td"><span><img src="/assets/images/usa.svg" alt=""></span> <span>United
                                States Dollar</span>
                            </div>
                            <div class="row-item-right-td">N 585</div>
                        </div>
                        <div class="rate-row-td bb-dd">
                            <div class="row-item-left-td"><span><img src="/assets/images/uk.svg" alt=""></span> <span>Great
                                Britain Pound</span>
                            </div>
                            <div class="row-item-right-td">N 585</div>
                        </div>
                        <div class="rate-row-td ">
                            <div class="row-item-left-td"><span><img src="/assets/images/eu.svg" alt=""></span> <span>European
                                Euro</span>
                            </div>
                            <div class="row-item-right-td">N 585</div>
                        </div>
                    </div>
                    <div class="ceda-rate">Convert to Local currency</div>
                    <div class="convert-local-currency">
                        <div class="upper-covert">
                            <div class="currency">
                                <div class="price-from">30</div>
                                <select name="price_to" id="price_to" class="price_to">
                                    <option value="DOL">DOL</option>
                                    <option value="POU">POU</option>
                                    <option value="EU">EU</option>
                                </select>
                            </div>
                            <div><img src="/assets/images/convert-in.svg" alt=""></div>
                            <div class="currency">
                                <div class="price-from">17,333</div>
                                <select name="price_to" id="price_to" class="price_to">
                                    <option value="DOL">DOL</option>
                                    <option value="POU">POU</option>
                                    <option value="EU">EU</option>
                                </select>
                            </div>
                        </div>
                        <div class="trans-btn-wrapper">
                            <div class="trans-btn">Continue Transaction</div>
                        </div>
                    </div>
                    <div class="ceda-rate">Account Activity</div>
                    <div class="convert-local-currency pd-table table-responsive-md">
                        <table class="table  table-borderless">
                            <thead>
                            <tr>
                                <th scope="col" class="blt">Description</th>
                                <th scope="col" class="blt">Date</th>
                                <th scope="col" class="blt">Amount</th>
                                <th scope="col" class="blt">Status</th>
                                <th scope="col" class="blt"></th>
                            </tr>
                            </thead>
                            <tbody class="bl">
                            <tr class="bl">
                                <th class="bl">Fund Conversion</th>
                                <td class="bl">01 Apr 2022</td>
                                <td class="bl">N 17,250</td>
                                <td class="bl"><span class="successful">Successful</span></td>
                                <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">--:--</span></td>
                            </tr>
                            <tr class="bl">
                                <th class="bl">Fund Conversion</th>
                                <td class="bl">01 Apr 2022</td>
                                <td class="bl">N 17,250</td>
                                <td class="bl"><span class="failed">Failed</span></td>
                                <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">--:--</span></td>
                            </tr>
                            <tr class="bl">
                                <th class="bl">Fund Conversion</th>
                                <td class="bl">01 Apr 2022</td>
                                <td class="bl">N 17,250</td>
                                <td class="bl"><span class="pending">Pending</span></td>
                                <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">12:04</span></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>