<?php include 'templates/footer.phtml'; ?>
<div class=" ceda-wrapper  plr">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right col-9-ceda">
                <div class="content-wrapper pt150">
                    <div class="right-header">
                        <div class="user-name"><span class="welcome">Hi,</span> <?= $_SESSION['name'] ?>! </div>
                    </div>

                </div>
                <!-- <div class="border-header"></div> -->
                <div class="content-wrapper bottom-content">



                    <div class="trans-box">
                        <div class="trans-box-left">
                            <div class="inner-left">
                            <div class="pending-left">Pending Transaction <span class="in-naira-left">(In Naira)</span></div>
                            <div class="timer"><Span><img src="/assets/images/time.svg" alt=""></Span> 00:04:04</div>
                            </div>

                            <div class="trans-price-left">₦ 585,200</div>
                         
                        </div>

                        <div class="trans-box-right">
                        <div class="total" >Total Transaction <span class="in-naira-right">(In Naira)</span></div>
                        <div class="trans-price-right">₦ 585,200</div>
                        </div>
                    </div>

                    <div class="ceda-container">
                        <div class="ceda-rate">Ceda Rate</div>
                        <div class="border-header"></div>
                        <div class="rate-row">
                            <div class="single-rate">
                                1 USD <span class="divider"><img src="/assets/images/usa.svg" alt=""></span> <span class="price">₦585</span>
                            </div>
                            <div class="single-rate">
                                1 GBP <span class="divider"><img src="/assets/images/uk.svg" alt=""></span> <span class="price">₦767</span>
                            </div>
                            <div class="single-rate">
                                1 EUR <span class="divider"><img src="/assets/images/eu.svg" alt=""></span> <span class="price">₦645</span>
                            </div>
                        </div>


                    </div>



                    <form action="" method="post">
                        <div class="convert-local-currency">
                            <div class="ceda-rate">Convert to Local currency</div>
                            <div class="upper-covert">

                                <div class="currency">
                                    <input type="number" class="price-from" id="entered_currency">
                                    <!--<div class="price-from no-border">30</div>-->
                                    <!--<select name="price_to" id="price_to" class="price_to">
                                        <option value="DOL">DOL</option>
                                        <option value="POU">POU</option>
                                        <option value="EU">EU</option>
                                    </select>-->
                                    <!--<select name="countries" id="price_to" class="price_to">
                                        <option value="usd">🇺🇸&emsp;USD</option>
                                        <option value="pou">🇬🇧&emsp;POU</option>
                                        <option value="eu">🇪🇺&emsp;EU</option>
                                    </select>-->
                                    <select name="countries" id="price_to" class="price_to">
                                        <?php foreach ($exchange_rates as $exchange_rate) { ?>
                                            <option value="<?= $exchange_rate['ceda_rate'] ?>"><?= $exchange_rate['currency_from_sign'] ?>&emsp;<?= $exchange_rate['currency_from'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="loop"><img src="/assets/images/convert-in.svg" alt=""></div>
                                <div class="currency">
                                    <!--<input type="number" class="price-from" id="price_to" placeholder="Price to">-->
                                    <div class="price-from no-border" id="converted_price">0</div>
                                    <!--<select name="price_to" id="price_to" class="price_to">
                                        <option value="DOL">DOL</option>
                                        <option value="POU">POU</option>
                                        <option value="EU">EU</option>
                                    </select>-->
                                    <div class="price_to" id="price_to"><span><img src="/assets/images/<?= $_SESSION['iso'] ?>.svg" alt="" class="converted_to_img"></span><span><?= $_SESSION['currency'] ?></span>
                                    </div>
                                </div>
                            </div>
                            <div class="trans-btn-wrapper">
                                <a href="#" class="trans-btn">Continue Transaction</a>
                            </div>
                        </div>
                    </form>

                    <div class="convert-local-currency pd-table table-responsive-md">
                        <div class="ceda-rate">Transactions</div>
                        <table class="table  table-borderless">
                            <thead>
                                <!-- <tr>
                                <th scope="col" class="blt">Description</th>
                                <th scope="col" class="blt">Date</th>
                                <th scope="col" class="blt">Amount</th>
                                <th scope="col" class="blt">Status</th>
                                <th scope="col" class="blt"></th>
                            </tr> -->
                            </thead>
                            <tbody class="bl">
                                <tr class="bl">
                                    <th class="bl">Fund Conversion</th>
                                    <td class="bl">01 Apr 2022</td>
                                    <td class="bl">N 17,250</td>
                                    <td class="bl"><span class="successful">Successful</span></td>
                                    <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">--:--</span></td>
                                </tr>
                                <tr class="bl">
                                    <th class="bl">Fund Conversion</th>
                                    <td class="bl">01 Apr 2022</td>
                                    <td class="bl">N 17,250</td>
                                    <td class="bl"><span class="failed">Failed</span></td>
                                    <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">--:--</span></td>
                                </tr>
                                <tr class="bl">
                                    <th class="bl">Fund Conversion</th>
                                    <td class="bl">01 Apr 2022</td>
                                    <td class="bl">N 17,250</td>
                                    <td class="bl"><span class="pending">Pending</span></td>
                                    <td class="bl"><img src="/assets/images/time.svg" alt=""><span class="time-text">12:04</span></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    //convertCurrency('30','185.27')
    $('#price_to').on('change', function() {
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })
    $('#entered_currency').keyup(function() {
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        $('#converted_price').html(numberWithCommas(convertCurrency(input, exchangeRate)));
    })
    $('.trans-btn').click(function(e) {
        e.preventDefault();
        let exchangeRate = $('#price_to').val();
        let input = $('#entered_currency').val();
        window.location.href = '/convert-to-local-currency?am=' + input + "&eq=" + convertCurrency(input, exchangeRate);
    })
</script>