<?php if ($title == "CEDA" || $title == 'Privacy' || $title == 'Terms Of Use') { ?>
    <footer class="bd-footer main-footer">
        <div class="container-header">
            <div class="logo-footer">
                <a href="/"><img src="./assets/images/cedaBlack.svg" alt="Ceda Logo"
                                 class=""></a>
            </div>
            <class class="bottom-row-footer">
                <div class="left-content-footer">
                    <div class="footer-right">
                        <div class="footer-link">
                            <a href="/login" class="link-item nav-bold">Convert Money</a>
                        </div>
                    </div>
                    <div class="footer-right footer-rightr">
                        <div class="footer-link">
                            <a href="/login" class="link-item nav-bold">int'l Bank Accounts</a>
                        </div>
                    </div>
                    <!-- <div class="footer-right" onclick="openModal()">
                        <div class="footer-link">
                            <a  class="link-item nav-bold">Business APIs</a>
                        </div>
                    </div> -->

                    <div class="footer-right">
                        <div class="footer-link">
                            <a href="/terms-of-use" class="link-item nav-bold">Terms of use</a>
                        </div>
                    </div>
                    <div class="footer-right">
                        <div class="footer-link">
                            <a href="/privacy" class="link-item privacy-footer nav-bold">Privacy Policy</a>
                        </div>
                    </div>
                </div>
                
                <div class="footer-left">
                    <p class="mb0 right-text">CedaMoney | 2022</p>
                </div>
            </class>
            <!--<div class="col-lg-2 ">
                <a class="d-inline-flex align-items-center mb-2 link-dark text-decoration-none footer-logo" href="/"
                   aria-label="Bootstrap">
                    <img src="./assets/images/cedaBlack.svg" alt="Ceda Logo"
                         class="footer-img">
                </a>
            </div>
            <div class="col-6 col-lg-2">
                <ul class="list-unstyled">
                    <li class="mb-4"><a class="footer-nav" href="/index">Individual</a></li>

                </ul>
            </div>
            <div class="col-6 col-lg-2">
                <ul class="list-unstyled">
                    <li class="mb-4"><a class="footer-nav" href="/business">Business</a></li>

                </ul>
            </div>
            <div class="col-6 col-lg-2">
                <ul class="list-unstyled">
                    <li class="mb-4"><a class="footer-nav" href="#">Help</a></li>

                </ul>
            </div>
            <div class="col-6 col-lg-2">
                <ul class="list-unstyled">
                    <li class="mb-4"><a class="footer-nav" href="/terms-of-use">Terms of use</a></li>

                </ul>
            </div>
            <div class="col-6 col-lg-2">
                <ul class="list-unstyled">
                    <li class="mb-4"><a class="footer-nav" href="/privacy">Privacy</a></li>

                </ul>
            </div>-->
        </div>
        <div id="myModal-h" class="mymodal-h">

            <!-- Modal content -->

            <div class="modal-content-h">

                <div class="modal_head-h">

                    <div class="modal-flex">
                        <div class="modal-heading-h">Business API </div>
                        <div class="close-modal-h"><span>&times;</span></div>
                    </div>


                    <div class="modal-text-h">Get access to the leading API solution for money conversion. A simple, secure, and
                        fast API to make changing money easy. Scale your money conversion business faster than
                        ever with our trusted & easy-to-use API!</div>

                </div>

                <div class="modal-title-h">Get Scalable Money Conversion API.</div>

                <div class="modal_body-h">
                        <div class="row">
                            <div class="col-lg-5">
                                <img src="/assets/images/coming-soon.png" class="coming-soon-img">
                            </div>
                            <div class="col-lg-7">
                                <p class="title-input-h">Full name </p>

                                <input type="text" PLACEHOLDER="Enter Full name" class="account-no-h">

                                <p class="title-input-h">Email </p>

                                <input type="email" PLACEHOLDER="Enter Email" class="account-no-h">

                                <p class="title-input-h">Phone Number </p>

                                <input type="text" PLACEHOLDER="Enter Phone Number" class="account-no-h">

                                <button class="btn-submit mt-20" id="add-bank-acc">Sign Me Up</button>
                            </div>
                        </div>

                </div>
            </div>

        </div>

    </footer>
<?php } ?>
<div id="snackbar"></div>
<script src="/assets/js/slim.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery-3.6.0.min.js"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script> -->
<script src="/assets/js/scripts.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/>
<script src="/assets/js/jquery.form.min.js"></script>
<script src="/assets/js/custom.js"></script>
<script src="https://cdn.tutorialjinni.com/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
<script>

    const openModal = ()=>{
        modal.style.display = "block";
    }
    function showToast() {
        let x = document.getElementById("snackbar");
        x.className = "showToast";
        setTimeout(function () {
            x.className = x.className.replace("show", "");
        }, 5000);
    }

    $('#open').click(function () {
        $('.show-on').show(150);
        // $('.hide-on').hide(150);
        $('#close').show()
        $(this).hide();
        $('.content-wrapper').addClass('pt-50');
    })
    $('#close').click(function () {
        $('.show-on').hide(150);
        $('#open').show();
        $(this).hide();
        $('.content-wrapper').removeClass('pt-50');

        // $('.hide-on').show(150);
    })
    const Base64 = {


        _keyStr: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",


        encode: function (input) {
            let output = "";
            let chr1, chr2, chr3, enc1, enc2, enc3, enc4;
            let i = 0;

            input = Base64._utf8_encode(input);

            while (i < input.length) {

                chr1 = input.charCodeAt(i++);
                chr2 = input.charCodeAt(i++);
                chr3 = input.charCodeAt(i++);

                enc1 = chr1 >> 2;
                enc2 = ((chr1 & 3) << 4) | (chr2 >> 4);
                enc3 = ((chr2 & 15) << 2) | (chr3 >> 6);
                enc4 = chr3 & 63;

                if (isNaN(chr2)) {
                    enc3 = enc4 = 64;
                } else if (isNaN(chr3)) {
                    enc4 = 64;
                }

                output = output + this._keyStr.charAt(enc1) + this._keyStr.charAt(enc2) + this._keyStr.charAt(enc3) + this._keyStr.charAt(enc4);

            }

            return output;
        },
        _utf8_encode: function (input) {
            input = input.replace(/\r\n/g, "\n");
            let utftext = "";

            for (let n = 0; n < input.length; n++) {

                let c = input.charCodeAt(n);

                if (c < 128) {
                    utftext += String.fromCharCode(c);
                } else if ((c > 127) && (c < 2048)) {
                    utftext += String.fromCharCode((c >> 6) | 192);
                    utftext += String.fromCharCode((c & 63) | 128);
                } else {
                    utftext += String.fromCharCode((c >> 12) | 224);
                    utftext += String.fromCharCode(((c >> 6) & 63) | 128);
                    utftext += String.fromCharCode((c & 63) | 128);
                }

            }

            return utftext;
        },

    }

    function encode(cipher) {

        const encodedString = Base64.encode(cipher)

        return encodedString;
    }
</script>

</body>
</html>