<div class="container ceda-wrapper plr">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right col-9-ceda">
                <div class="content-wrapper pt150">
                    <div class="right-header">
                        <h3 class="header-text">
                            Get Freelancing Advice
                        </h3>
                    </div>

                </div>
                <div class="border-header"></div>
                <div class="content-wrapper">
                    <div class="content">
                        <div class="view-content">
                            <div class="title-content">
                                <img src="/assets/images/reqacall.svg" alt="" class="title-img">
                                <div class="actual-title">
                                    <p class="m0 reqcall">Request a call</p>

                                </div>
                            </div>
                            <img src="/assets/images/arrow-right.svg" alt="" class="arrow-right">
                            <img src="/assets/images/arrow-down.svg" alt="" class="arrow-down">
                        </div>
                        <button class="sendreq-btn">Send Request</button>
                    </div>
                    <div class="content">
                        <div class="view-content">
                            <div class="title-content">
                                <img src="/assets/images/emailus.svg" alt="" class="title-img">
                                <div class="actual-title">
                                    <p class="m0 reqcall">Email Us</p>

                                </div>
                            </div>
                            <img src="/assets/images/arrow-right.svg" alt="" class="arrow-right-email">
                            <img src="/assets/images/arrow-down.svg" alt="" class="arrow-down-email">
                        </div>
                        <div class="emailuson">
                            <p class="m0 emailto">Send mail to:</p>
                            <div class="email-address">
                                <p class="m0 email-address-text">cedafinance@ceda.com</p>
                                <img src="/assets/images/copy-email.svg" alt="" class="copy-email">
                            </div>
                        </div>
                    </div>
                    <div class="content">
                        <div class="view-content">
                            <div class="title-content">
                                <img src="/assets/images/later.svg" alt="" class="title-img">
                                <div class="actual-title">
                                    <p class="m0 reqcall">Schedule for a later call</p>

                                </div>
                            </div>
                            <img src="/assets/images/arrow-right.svg" alt="" class="arrow-right-later">
                            <img src="/assets/images/arrow-down.svg" alt="" class="arrow-down-later">
                        </div>
                        <button class="sendreq-btn">Send Request</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include 'templates/footer.phtml'; ?>
<script>
    $('.arrow-right').click(function(e){
        e.preventDefault();
        $(this).hide();
        $('.arrow-down').show();
        $('.sendreq-btn').show(150);
    })
    $('.arrow-down').click(function(e){
        e.preventDefault();
        $(this).hide();
        $('.arrow-right').show();
        $('.sendreq-btn').hide(150);
    })
    /***********email************/
    $('.arrow-right-email').click(function(e){
        e.preventDefault();
        $(this).hide();
        $('.arrow-down-email').show();
        $('.emailuson').show(150);
    })
    $('.arrow-down-email').click(function(e){
        e.preventDefault();
        $(this).hide();
        $('.arrow-right-email').show();
        $('.emailuson').hide(150);
    })
    /**************later***************/
    $('.arrow-right-later').click(function(e){
        e.preventDefault();
        $(this).hide();
        $('.arrow-down-later').show();
        $('.sendreq-btn').show(150);
    })
    $('.arrow-down-later').click(function(e){
        e.preventDefault();
        $(this).hide();
        $('.arrow-right-later').show();
        $('.sendreq-btn').hide(150);
    })
</script>
