<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name=”viewport” content=”width=device-width,initial-scale=1.0">
    <link rel="icon" href="./assets/images/favicon.svg">

    <title><?= $title ?></title>

    <!-- Font-awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="./assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="./assets/styles.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--        <link href="./assets/css/dash-styles.css" rel="stylesheet" />-->

    <?php if ($title == 'Privacy Notices | We Remind' || $title == "Terms & Conditions | We Remind") { ?>
        <link href="./assets/css/privacy-style.css" rel="stylesheet"/>
    <?php } ?>
    <link rel="stylesheet" href="https://cdn.tutorialjinni.com/intl-tel-input/17.0.8/css/intlTelInput.css"/>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>
<body>
<?php if ($title == "CEDA" || $title == 'Privacy' || $title == 'Terms Of Use') { ?>
    <style>
        /* CSS used here will be applied after bootstrap.css */

        .nav {
            margin-bottom: 0;
        }

        .nav > li.dropdown.open {
            position: static;
        }

        .nav > li.dropdown.open .dropdown-menu {
            display: block;
            width: 100%;
        }

        .dropdown-menu > li {
            display: block;
        }

    </style>
    <div class="top-header">
        <div class="container-header">
            <div class="row">
                <div class="col-md-6">
                    <p class="top-header-text mb0">With Ceda, you can send money anywhere in the world with ease.</p>
                </div>
                <div class="col-md-6 top-right-content">
                    <a href="#" class="career">Careers</a>
                    <div class="top-line">
                        <img src="/assets/images/top-line.svg" class="top-img" alt="line">
                    </div>
                    <a href="https://www.instagram.com/cedamoney/" target="_blank"><img
                                src="/assets/images/top-insta.svg" class="top-img" alt="CEDA Instagram"></a>
                    <a href="#" target="_blank"><img src="/assets/images/top-fb.svg" class="top-img"
                                                     alt="CEDA Facebook"></a>
                    <a href="https://www.linkedin.com/in/cedamoney/" target="_blank"> <img
                                src="/assets/images/top-linkedin.svg" class="top-img" alt="CEDA LinkedIn"></a>
                </div>
            </div>
        </div>
    </div>
    <div class="down-header">
        <div class="container-header-">
            <!---------->
            <nav class="navbar navbar-expand-lg my-header">

                <a href="/" class="navbar-brand logo-wrapper"><img src="./assets/images/cedaBlack.svg" alt="Ceda Logo"
                                                                   class=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="fa fa-bars"></i></span>
                </button>


                <div class="collapse navbar-collapse header-right" id="navbarText" style="">

                    <ul class="navbar-nav">
                        <li class="nav-item nav-item-ceda dropdown-list-item-ceda convert-header-wrapper">
                            <a href="#" class="nav-link dropdown-toggle list-name-ceda convert-moneny-header"
                               data-toggle="dropdown">Convert Money</a>
                            <ul class="dropdown-menu dropdown-header-main convert-ul">
                                <div clas="header-row-drop">
                                    <li>
                                        <div class="header-row-drop">
                                            <div class="list-unstyled coverage col-md-4">
                                                <p class="submenu-title mb0 coverage-title">Coverage</p>
                                                <div class="coverage-area-wrapper">
                                                    <div class="coverage-areas ">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/ng-coverage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-active">Nigeria</p>
                                                            <div class="coverage-active">Active</div>
                                                        </div>
                                                    </div>
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/kenya-coverage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-in">Kenya</p>

                                                            <div class="coverage-inactive">Inactive</div>
                                                        </div>
                                                    </div>
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/togo-overage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-in">Togo</p>

                                                            <div class="coverage-inactive">Inactive</div>
                                                        </div>
                                                    </div>
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/ghana-coverage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-in">Ghana</p>

                                                            <div class="coverage-inactive">Inactive</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-8 right-sec-drop">
                                                <div class="header-row-drop right-sec-row">
                                                    <div class="list-unstyled col-md-4">
                                                        <div class="dropdown-right-content mb56">

                                                            <div class="titles-sub">
                                                                <img src="/assets/images/local-bank.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">Convert
                                                                    from Local
                                                                    Bank</a>
                                                            </div>
                                                            <div class="titles-sub">
                                                                <div class="w36px"></div>
                                                                <p class="mb0 lower-drop">Lörem ipsum anasade jäss</p>

                                                            </div>

                                                        </div>
                                                        <div class="dropdown-right-content mb56-mob">

                                                            <div class="titles-sub">
                                                                <img src="/assets/images/header-payoneer.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">Convert
                                                                    Payoneer
                                                                    Fund</a>
                                                            </div>
                                                            <div class="titles-sub">
                                                                <div class="w36px"></div>
                                                                <p class="mb0 lower-drop">Lörem ipsum anasade jäss</p>

                                                            </div>

                                                        </div>

                                                    </div>
                                                    <div class="list-unstyled col-md-4">
                                                        <div class="dropdown-right-content mb56">

                                                            <div class="titles-sub">
                                                                <img src="/assets/images/us-bank.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">Convert
                                                                    from US Bank</a>
                                                            </div>
                                                            <div class="titles-sub">
                                                                <div class="w36px"></div>
                                                                <p class="mb0 lower-drop">Lörem ipsum anasade jäss</p>

                                                            </div>

                                                        </div>
                                                        <div class="dropdown-right-content mb56-mob">

                                                            <div class="titles-sub">
                                                                <img src="/assets/images/convert-wise-icon.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">Convert
                                                                    Wise funds</a>
                                                            </div>
                                                            <div class="titles-sub">
                                                                <div class="w36px"></div>
                                                                <p class="mb0 lower-drop">Lörem ipsum anasade jäss</p>

                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="list-unstyled col-md-4 mb56 mb0">
                                                        <div class="dropdown-right-content ">

                                                            <div class="titles-sub">
                                                                <img src="/assets/images/card.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">Convert
                                                                    from Card</a>
                                                            </div>
                                                            <div class="titles-sub">
                                                                <div class="w36px"></div>
                                                                <p class="mb0 lower-drop">Lörem ipsum anasade jäss</p>

                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </div>
                            </ul>
                        </li>
                        <li class="nav-item nav-item-ceda dropdown-list-item-ceda international-wrapper">
                            <a href="#" class="nav-link dropdown-toggle list-name-ceda international"
                               data-toggle="dropdown">Int’l Bank
                                Accounts</a>
                            <ul class="dropdown-menu dropdown-header-main international-ul">
                                <div clas="header-row-drop">
                                    <li>
                                        <div class="header-row-drop">
                                            <div class="list-unstyled coverage col-md-4">
                                                <p class="submenu-title mb0 coverage-title">Coverage</p>
                                                <div class="coverage-area-wrapper">
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/ng-coverage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-active">Nigeria</p>
                                                            <div class="coverage-active">Active</div>
                                                        </div>
                                                    </div>
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/kenya-coverage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-in">Kenya</p>

                                                            <div class="coverage-inactive">Inactive</div>
                                                        </div>
                                                    </div>
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/togo-overage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-in">Togo</p>

                                                            <div class="coverage-inactive">Inactive</div>
                                                        </div>
                                                    </div>
                                                    <div class="coverage-areas">
                                                        <div class="coverage-list">
                                                            <img src="/assets/images/ghana-coverage.svg" alt=""
                                                                 class="coverage-flag">
                                                            <p class="mb0 country-name-in">Ghana</p>

                                                            <div class="coverage-inactive">Inactive</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-8 right-sec-drop">
                                                <div class="header-row-drop right-sec-row">
                                                    <div class="list-unstyled col-md-4">
                                                        <div class="dropdown-right-content mb56">
                                                            <div class="titles-sub alc">
                                                                <img src="/assets/images/eu-header.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">Euro Bank
                                                                    Account</a>
                                                                <img src="/assets/images/arrow-header.svg" alt="">
                                                            </div>
                                                        </div>
                                                        <div class="dropdown-right-content mb56-mob">
                                                            <div class="titles-sub alc">
                                                                <img src="/assets/images/ngn-header.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">NGN Bank
                                                                    Account</a>
                                                                <img src="/assets/images/arrow-header.svg" alt="">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="list-unstyled col-md-4">
                                                        <div class="dropdown-right-content mb56">

                                                            <div class="titles-sub alc">
                                                                <img src="/assets/images/gbp-header.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">GBP Bank
                                                                    Account</a>
                                                                <img src="/assets/images/arrow-header.svg" alt="">

                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="list-unstyled col-md-4">
                                                        <div class="dropdown-right-content mb56 mb0">

                                                            <div class="titles-sub alc">
                                                                <img src="/assets/images/usd-header.svg" alt=""
                                                                     class="icon-drop">
                                                                <a href="/login" class="mb0 right-title-drop">USD Bank
                                                                    Account</a>
                                                                <img src="/assets/images/arrow-header.svg" alt="">
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </div>
                            </ul>
                        </li>
                        <li class="nav-item nav-item-ceda" onclick="openModal()">
                            <a class="nav-link nav-ceda list-name-ceda">Business APIs</a>
                        </li>

                        <li class="nav-item nav-item-ceda">
                            <a class="nav-link nav-ceda list-name-ceda" href="javascript:"
                               onclick="tidioChatApi.display(true);tidioChatApi.open()"> Live Chat <img
                                        class="live-chat"
                                        src="/assets/images/live-chat.svg" alt=""></a>
                        </li>
                    </ul>
                    <span class="navbar-text btn-mobile">
                <div class="form-inline my-2 my-lg-0">
                    <a class="mr-4s login-account" href="/login">Login to account</a>
                </div>
                </span>


                </div>
            </nav>

            <div id="myModal" class="mymodal">

                <!-- Modal content -->
                <div class="close-modal"><span>&times;</span></div>
                <div class="modal-content">

                    <div class="modal_head">

                        <div class="modal-heading">Business APIs Coming Soon</div>

                        <div class="modal-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>

                    </div>

                    <div class="modal_body">

                        <p class="title-input">Fullname </p>

                        <input type="text" PLACEHOLDER="Enter Fullname" class="account-no">

                        <p class="title-input">Email </p>

                        <input type="email" PLACEHOLDER="Enter Email" class="account-no">

                        <p class="title-input">Phone Number </p>

                        <input type="text" PLACEHOLDER="Enter Phone Number" class="account-no">

                        <button class="btn-submit m0 m40" id="add-bank-acc">Proceed</button>
                    </div>
                </div>

            </div>

            <script src="//code.tidio.co/ouwhjlrqllifkhobctz1kxhobnfjyfcz.js" async>

            </script>
            <script>

                let modal = document.getElementById("myModal");

                let span = document.getElementsByClassName("close-modal")[0];
                const openModal = () => {
                    modal.style.display = "block";
                }
                span.onclick = function () {
                    modal.style.display = "none";
                }

                window.onclick = function (event) {
                    if (event.target == modal) {
                        modal.style.display = "none";
                    }
                }

            </script>
            <!---------->

            <!-- <?php if ($_SESSION['id'] == "") { ?>
    <div class="form-inline my-2 my-lg-0">
       <a class="mr-4 text-dark login-account" href="/login">Login to account</a>
        <a class="btn btn-primary my-2 my-sm-0 text-white" href="/signup" type="submit">Sign Up</a>
    </div>
    <?php } else { ?>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
        <li class="nav-item active"><div class="nav-link logout">Logout</div></li>
    </ul>
  </div>
  <?php } ?> -->
        </div>
    </div>
<?php } ?>
<?php if ($title == 'Dashboard' || $title == 'Settings' || $title == 'Convert Money' || $title == 'Transfer' || $title == 'Transaction' || $title == 'KYC Verification') { ?>
<div class="flexBar">
    <div>
        <a href="index">
            <img src="./assets/images/ceda-sidebar.svg" alt="CEDA logo">

        </a>
    </div>
    <i class="fa fa-bars" id="open"></i>
    <i class="fa fa-times" id="close"></i>

</div>
<div class="col-md-12 ceda-wrapper show-on hide-on-desktop">
    <div class="sidebar-wrapper">
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item nav-li">
                <a href="/dashboard" class="nav-link  sidebar-nav <?= ($title == "Dashboard") ? 'selected' : '' ?>"
                   aria-current="page">
                    <img class="nav-icons" src="/assets/images/home<?= ($title == 'Dashboard') ? '' : '-in' ?>.svg"
                         alt="home-icon">
                    <span class="<?= ($title == "Dashboard") ? 'sidebar-title-active' : 'sidebar-title' ?>">Home</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/convert-money"
                   class="nav-link  sidebar-nav  <?= ($title == "Convert Money") ? 'selected' : '' ?>"
                   aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/convert<?= ($title == 'Convert Money') ? '' : '-in' ?>.svg"
                         alt="convert-to-local-icon">
                    <span class="<?= ($title == "Convert Money") ? 'sidebar-title-active' : 'sidebar-title' ?>">Convert Money</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="#" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/dollar<?= ($title == 'Sell Digital Products') ? '' : '-in' ?>.svg"
                         alt="sell-digital-products-icon">
                    <span class="<?= ($title == "Sell Digital Products") ? 'sidebar-title-active' : 'sidebar-title' ?>">Intl. Bank Accounts <br> for Salary & Payments</span>
                    <!--                    <span class="coming-soon">Coming Soon</span>-->
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/transaction" class="nav-link  sidebar-nav <?= ($title == "Transaction") ? 'selected' : '' ?>"
                   aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/transaction<?= ($title == 'Transaction') ? '' : '-in' ?>.svg"
                         alt="transactions-icon">
                    <span class="<?= ($title == "Transaction") ? 'sidebar-title-active' : 'sidebar-title' ?>">Transactions</span>

                </a>
            </li>
            <!-- <li class="nav-item nav-li">
                <a href="/get-freelancing-advice" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/transaction<?= ($title == 'Get Freelancing Advice') ? '' : '-in' ?>.svg"
                         alt="sell-digital-products-icon">
                    <span class="<?= ($title == "Get Freelancing Advice") ? 'sidebar-title-active' : 'sidebar-title' ?>">Get Freelancing Advice</span>

                </a>
            </li> -->
            <li class="nav-item nav-li">
                <a href="/settings" class="nav-link sidebar-nav <?= ($title == "Settings") ? 'selected' : '' ?>"
                   aria-current="page">
                    <img class="nav-icons" src="/assets/images/setting<?= ($title == 'Settings') ? '' : '-in' ?>.svg"
                         alt="setting-icon">
                    <span class="<?= ($title == "Settings") ? 'sidebar-title-active' : 'sidebar-title' ?>">Settings</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/logout" class="nav-link sidebar-nav aria-current=" page">
                <img class="nav-icons" src="/assets/images/logout.svg"
                     alt="setting-icon">
                <span class="sidebar-title">Log out</span>
                </a>
            </li>
        </ul>
    </div>
</div>

<?php } ?>