<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name=”viewport” content=”width=device-width,initial-scale=1.0">
    <!--<link rel="icon" href="./assets/images/weremind-favicon.png">-->

    <title><?= $title ?></title>

    <!-- Font-awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="./assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="./assets/styles.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--        <link href="./assets/css/dash-styles.css" rel="stylesheet" />-->

    <?php if ($title == 'Privacy Notices | We Remind' || $title == "Terms & Conditions | We Remind") { ?>
        <link href="./assets/css/privacy-style.css" rel="stylesheet"/>
    <?php } ?>
    <link rel="stylesheet" href="https://cdn.tutorialjinni.com/intl-tel-input/17.0.8/css/intlTelInput.css"/>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>
<body>
<?php if ($title == "CEDA" || $title == 'Privacy' || $title == 'Terms Of Use') { ?>
    <div class="container">
        <!---------->
        <nav class="navbar navbar-expand-lg my-header">
   
                <a href="/" class="navbar-brand logo-wrapper"><img src="./assets/images/cedaBlack.png" alt="Ceda Logo" class=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="fa fa-bars"></i></span>
                </button>
       
            
            <div class="collapse navbar-collapse" id="navbarText" style="">
                
                    <ul class="navbar-nav mr-auto float-r">
                        <li class="nav-item nav-item-ceda">
                            <a class="nav-link nav-ceda" href="/index"> Individual </a>
                        </li>
                        <li class="nav-item nav-item-ceda">
                            <a class="nav-link nav-ceda" href="/business">Business</a>
                        </li>

                        <li class="nav-item nav-item-ceda">
                            <a class="nav-link nav-ceda" href="#"> Help</a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                <div class="form-inline my-2 my-lg-0">
                    <a class="mr-4s login-account" href="/login">Login to account</a>
                </div>
                </span>
                    
                
            </div>
        </nav>
        <!---------->

        <!-- <?php if ($_SESSION['id'] == "") { ?>
    <div class="form-inline my-2 my-lg-0">
       <a class="mr-4 text-dark login-account" href="/login">Login to account</a>
        <a class="btn btn-primary my-2 my-sm-0 text-white" href="/signup" type="submit">Sign Up</a>
    </div>
    <?php } else { ?>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
        <li class="nav-item active"><div class="nav-link logout">Logout</div></li>
    </ul>
  </div>
  <?php } ?> -->
    </div>
<?php } ?>
<?php if ($title == 'Dashboard' || $title == 'Settings'|| $title == 'Covert To Local Currency' || $title == 'Transfer' || $title == 'KYC Verification') { ?>
<div class="flexBar">
    <div>
        <a href="index">
            <img src="./assets/images/ceda-sidebar.svg" alt="CEDA logo">

        </a>
    </div>
    <i class="fa fa-bars" id="open"></i>
    <i class="fa fa-times" id="close"></i>

</div>
<div class="col-md-12 ceda-wrapper show-on hide-on-desktop">
    <div class="sidebar-wrapper">
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item nav-li">
                <a href="/dashboard" class="nav-link  sidebar-nav <?= ($title == "Dashboard") ? 'selected' : '' ?>"
                   aria-current="page">
                    <img class="nav-icons" src="./assets/images/home<?= ($title == 'Dashboard') ? '' : '-in' ?>.svg"
                         alt="home-icon">
                    <span class="<?= ($title == "Dashboard") ? 'sidebar-title-active' : 'sidebar-title' ?>">Home</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/convert-to-local-currency"
                   class="nav-link  sidebar-nav  <?= ($title == "Covert To Local Currency" || $title == 'Transfer') ? 'selected' : '' ?>"
                   aria-current="page">
                    <img class="nav-icons"
                         src="./assets/images/convert<?= ($title == 'Covert To Local Currency' || $title == 'Transfer') ? '' : '-in' ?>.svg"
                         alt="convert-to-local-icon">
                    <span class="<?= ($title == "Covert To Local Currency" || $title == 'Transfer') ? 'sidebar-title-active' : 'sidebar-title' ?>">Convert to Local Currency</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="#" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons"
                         src="./assets/images/dollar<?= ($title == 'Sell Digital Products') ? '' : '-in' ?>.svg"
                         alt="sell-digital-products-icon">
                    <span class="<?= ($title == "Sell Digital Products") ? 'sidebar-title-active' : 'sidebar-title' ?>">Sell Digital Products</span>
                    <span class="coming-soon">Coming Soon</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/settings" class="nav-link sidebar-nav <?= ($title == "Settings") ? 'selected' : '' ?>""
                aria-current="page">
                <img class="nav-icons" src="./assets/images/setting<?= ($title == 'Settings') ? '' : '-in' ?>.svg"
                     alt="setting-icon">
                <span class="<?= ($title == "Settings") ? 'sidebar-title-active' : 'sidebar-title' ?>">Settings</span>
                </a>
            </li>
        </ul>
    </div>
</div>

<?php } ?>