<section class="hero-section">
    <div class="hero-bg">
        <div class="container hero-container">
            <div class="row hero-row">
                <div class="col-md-6 hero-content">

                    <h2 class="hero-heading">Simplify Money for Freelancers</h2>
                    <p class="hero-description">Get the best exchange rates on Ceda and change your money easily. Send
                        and receive money anywhere in the world at your convenience. </p>
                    <div class="join-ceda">
                        <a href="/register" class="btn btn-get-start-cta">Get started today</a>
                    </div>
                </div>
                <div class="col-md-6 hero-content">

                    <img class="side-img" src="/assets/images/hero-img-facelift.svg" alt="CEDA Banner">

                </div>
            </div>
        </div>
    </div>
</section>


<!------------Convert Section------------->

<section class="convert">
    <div class="container">
        <div class="convert-wrapper-main">
            <div class="row row-sb">
                <div class="convert-content">
                    <p class="mb0 convert-title">Convert</p>
                    <div class="dropdown show dropdown-convert-wrapper">
                        <a class="btn btn-secondary dropdown-toggle dropdown-btn-convert" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="/assets/images/usa.svg" alt="">
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                    <div class="convert-right-content">
                        <input type="number" class="price-from" id="entered_currency">
                        <img src="/assets/images/line-convert.svg" alt="">
                        <p class="mb0 currency-name">USD</p>
                    </div>
                </div>
                <div class="convert-content">
                    <p class="mb0 convert-title">Value</p>
                    <div class="dropdown show dropdown-convert-wrapper">
                        <a class="btn btn-secondary dropdown-toggle dropdown-btn-convert" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="/assets/images/usa.svg" alt="">
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                    <div class="convert-right-content">
                        <input type="number" class="price-from" id="entered_currency">
                        <img src="/assets/images/line-convert.svg" alt="">
                        <p class="mb0 currency-name">USD</p>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!------------Faq section ------------->
<section class="faq-sec">
    <div class="container">
        <div class="faq" id="faq">


            <div class="show-faq">
                <div class="flex q">
                    <p class="faqQues">How long does it take to build a Product ? </p>
                    <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>


                </div>


                <div class="faqAns hide">
                    <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                    </p>
                </div>

            </div>


        </div>
        <div class="show-faq">
            <div class="flex q">
                <p class="faqQues">How long does it take to build a Product ? </p>
                <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>


            </div>


            <div class="faqAns hide">
                <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                </p>
            </div>

        </div>
        <div class="show-faq">
            <div class="flex q">
                <p class="faqQues">How long does it take to build a Product ? </p>
                <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>


            </div>


            <div class="faqAns hide">
                <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                </p>
            </div>

        </div>
        <div class="show-faq">
            <div class="flex q">
                <p class="faqQues">How long does it take to build a Product ? </p>
                <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>


            </div>


            <div class="faqAns hide">
                <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                </p>
            </div>

        </div>
        <div class="show-faq">
            <div class="flex q">
                <p class="faqQues">How long does it take to build a Product ? </p>
                <i class="fa fa-plus plus icon-faq" aria-hidden="true"></i>


            </div>


            <div class="faqAns hide">
                <p>Even though we’d hate to see you go, you can cancel your subscription at any time.
                </p>
            </div>

        </div>


    </div>


    </div>
    </div>

</section>

<script>

    function faqControl() {
        $(".faqAns").hide();
        $(".q").on("click", function () {

            if ($(this).next(".faqAns").hasClass("active")) {
                $(this).next().slideToggle().removeClass("active");
                $(this).children("i").removeClass("fa-minus").addClass("fa-plus")
            } else {
                $(this).next().slideToggle().addClass("active");
                $(this).children("i").removeClass("fa-plus").addClass("fa-minus")


            }
        });
    }

    $(document).ready(function () {
        faqControl()

    });


</script>
<?php include 'templates/footer.phtml'; ?>