<section class="hero-section">
    <div class="container"> 
        <div class="row hero-row">
            <div class="col-md-6">
                <div class="inner-col">
                    <h2 class="hero-heading">The platform that makes freelancer easy</h2>
                    <p class="hero-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                    <p class="hero-about">Join 180,000+ people ready for Smart Money.</p>
                    <a href="#" class="btn btn-get-start-cta">Get started today</a>
                    <a href="#" class="btn btn-get-hiw-cta">How it works</a>
                    <p class="hero-login"><a href="#">Login into account <img src="/assets/images/arrow.png" alt="Ceda arrow"></a></p>
                </div>                
            </div>
            <div class="col-md-6">
                <div class="inner-col">
                    <img class="section-image" src="/assets/images/hero-banner.png" alt="Ceda hero">
                </div>
            </div>
        </div>
    </div>
</section>
<!------------Currency Exchange------------->
<section class="currency-exchange-section">
    <div class="container"> 
        <div class="row currency-exchange-row">
            <div class="col-md-6">
                <div class="inner-col">
                    <h2 class="section-heading">Currency Exchange</h2>
                    <p class="section-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                    <div class="section-sub-detail">
                        <h3 class="section-sub-heading">Currency Exchange</h3>
                        <p class="section-sub-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                        <h3 class="section-sub-heading">Currency Exchange</h3>
                        <p class="section-sub-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                    </div>
                </div>                
            </div>
            <div class="col-md-6">
                <div class="inner-col">
                    <img class="section-image" src="/assets/images/IconBusiness.png" alt="Ceda hero">
                </div>
            </div>
        </div>
    </div>
</section>
<!------------Sell digital service or product internationally------------->
<section class="digital-service-section">
    <div class="container"> 
        <div class="row hero-row">            
            <div class="col-md-6">
                <div class="inner-col">
                    <img class="section-image" src="/assets/images/hero-banner.png" alt="Ceda hero">
                </div>
            </div>
            <div class="col-md-6">
                <div class="inner-col">
                    <h2 class="section-heading">Sell digital service or product internationally</h2>
                    <p class="section-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                    <div class="section-sub-detail">
                        <h3 class="section-sub-heading">Currency Exchange</h3>
                        <p class="section-sub-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                        <h3 class="section-sub-heading">Currency Exchange</h3>
                        <p class="section-sub-description">It's one simple platform for Currency exchange, Foreign Account, Sell digital service or product Internationally, Micro Business Account, Micro Business POS and much more.</p>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</section>