<div class="container ceda-wrapper plr">
    <div class="col-md-12 ceda-wrapper">
        <div class="row w100">
            <?php include "sidebar.phtml" ?>
            <div class="col-md-9 ceda-wrapper bg-right col-9-ceda">
                <div class="content-wrapper pt150 pb-27">
                    <div class="right-header">
                        <h3 class="header-text">
                            <span class="back"><a href="/"><img src="/assets/images/back.svg" alt="back"></a></span> KYC
                            Verification & Local Bank Details
                        </h3>
                    </div>

                </div>
                <div class="border-header"></div>
                <div class="content-wrapper ">
                    <div class="licences-wrapper">
                        <p class="m0 kyc-title">KYC Verification</p>
                        <p class="m0 kyc-sub-title">Upload Driver license or Passport?</p>
                        <form id="kyc_form" method="post" action="/ajax/insert_kyc_data" enctype="multipart/form-data">

                            <div class="image-wrapper">
                                <div class="box__input">
                                    <span class="small-upload"><img src="/assets/images/small-upload.svg"></span>
                                    <span class="btn-file m0 label-kyc">
                                     Choose a file or drag it here  <input type="file" name="file" id="file"
                                           onchange="readURL(this);" style="width: 100%;height: 110px;"/>
                                    </span>
                                    <p class="m0 size-limit">Size limit: 10MB</p>
                                    <img style="display: none" src="" alt="img" id="selectedImg">
                                </div>
                            </div>
                            <div class="bank-details">
                                <p class="m0 detail-title">Bank details to receive funds</p>
                                <div class="bank_section">
                                    <p class="m0 bank-name">
                                        Bank Name
                                    </p>
                                    <select name="bank_name" id="bank_name" class="form-control bank_name_wrapper">
                                        <option value="Habbib bank limited">Habbib bank limited</option>
                                        <option value="Habbib bank limited">Habbib bank limited</option>
                                        <option value="Habbib bank limited">Habbib bank limited</option>
                                    </select>
                                </div>
                                <div class="bank_section">
                                    <p class="m0 bank-name">
                                        Account Full Name
                                    </p>
                                    <input type="text" class="form-control bank_name_wrapper" disabled name="account_name"
                                           value="<?= $_SESSION['name'] ?>">
                                </div>
                                <div class="bank_section">
                                    <p class="m0 bank-name">
                                        Account Number
                                    </p>
                                    <input type="text" class="form-control bank_name_wrapper" name="account_number"
                                           placehol der="Account Number">
                                </div>
                                <button type="submit" class="btn-send">Submit <span class="sub-btn-kyc"><img
                                                src="/assets/images/submit.svg" alt=""></span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include 'templates/footer.phtml'; ?>
<script>

    // $('.btn-send').click(function (e) {
    //     e.preventDefault();
    //
    // });
    $('#kyc_form').on('submit',function (e){
        e.preventDefault();
        $(this).ajaxSubmit({
            //	target: '#output',
            dataType:  'json',
            success:  showResponse //call function after success
        });
    });
    function showResponse(res){
        if(res.upload_error!=undefined) {
            $('#snackbar').html(res.upload_error);
            showToast();
            return;
        }
        if(res.error!=undefined) {
            $('#snackbar').html(res.error);
            showToast();
            return;
        }
        if(res.message!=undefined) {
            $('#snackbar').html(res.message);
            showToast();
            return;
        }
    }
</script>