
<section class="login-service-section">
    <div class="container-fluid">
        <div class="row login-row col-rev-ceda">
            <div class="col-md-5 left-col hl-150">
                <div class="inner-col">
                    <a href="/">  <img src="./assets/images/Ceda-Black.svg" class="sign-img" alt="CEDA Logo"></a>
                    <h2 class="left-content">A new world of financial possibilities is within reach with Ceda.</h2>
                    <p class="left-content-text">Enjoy seamless currency exchange and conduct international transactions with ease.</p>
                </div>
                <img src="/assets/images/sign-img.png" class="left-col-img">
            </div>
            <div class="col-md-7 right-col others">
                <div class="inner-col">
                    <h2 class="form-heading">Welcome back</h2>
                    <p class="contact-form-sub-heading">Please enter your account details</p>
                    <form action="" class="right-form">
                        <div class="form-group">
                            <label class="form-labels" for="email">Email Address</label>
                            <input type="email" class="form-control input-login" id="email" name="email" placeholder="Enter your email address">
                        </div>
                        <div class="form-group">
                            <label class="form-labels" for="password">Enter Password</label>
                            <div class="input-group pass-wrapper pl-0" id="show_hide_password">
                                <input class="form-control input-login login-pass" type="password" name="password" id="password" placeholder="Min. of 8 characters">
                                <div class="input-group-addon show">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                </div>
                                <div class="input-group-addon hide">
                                    <i class="fa fa-eye-slash" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="text-right forgot-pass">
                            <a class="forgot-password-login" href="/reset-password">Forgot Password?</a>
                        </div>
                        <button class="btn-submit mt-24">Login &nbsp; <img src="/assets/images/register.png" alt=""></button>
                        <div class="register-redirect">
                            No account yet? <a href="/register">Register here</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include 'templates/footer.phtml'; ?>
<script>
    $('.btn-submit').click(function(e){
        e.preventDefault();
        if($('#email').val() ==''){
            $('#snackbar').html('Please enter your email');
            showToast();
            return;
        }
        if($('#password').val() ==''){
            $('#snackbar').html('Please enter password');
            showToast();
            return;
        }
            //$(this).html(` <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>`)
            try{
                $.ajax({
                    url: '/ajax/login_user',
                    method: 'POST',
                    dataType: 'JSON',
                    data: {
                        email: $('#email').val(),
                        password: $('#password').val(),
                    },
                    success: function (data) {
                        // $(this).html(`<p>Register</p> &nbsp; <img src="/assets/images/register.png" alt="">`)
                        if(data.message!==undefined) {
                            $('#snackbar').html(data.message);
                            // showToast();
                            setTimeout(function () {
                                window.location.href="/dashboard";
                            },1000)

                        }
                        else{
                            $('#snackbar').html(data.error);
                            showToast();
                        }
                    }
                });
            }catch(e){
                console.warn(e)
            }


    })

    $('.show').click(function(){
        $(this).hide();
        $('.hide').show();
        $( "#password" ).attr( "type", "password" );
    })
    $('.hide').click(function(){
        $(this).hide();
        $('.show').show();
        $( "#password" ).attr( "type", "text" );
    })
</script>
