
<section class="login-service-section">
    <div class="container-fluid">
        <div class="row login-row">
            <div class="col-md-5 left-col">
                <div class="inner-col">
                    <a class="d-inline-flex align-items-center mb-2 link-dark text-decoration-none" href="/" aria-label="Bootstrap">
                        <img src="/assets/images/footer-logo.png" alt="CEDA Logo">
                    </a>
                    <h2 class="left-content">Lorem ipsum is placeholder text commonly</h2>
                    <p class="left-content-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="col-md-7 right-col">
                <div class="inner-col">
                    <h2 class="form-heading">Welcome back</h2>
                    <p class="contact-form-sub-heading">Please enter your account details</p>
                    <form action="">
                        <div class="form-group">
                            <label for="inputEmail">Email Address</label>
                            <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label for="inputEmail">Email Password</label>
                            <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include 'templates/footer.phtml'; ?>