
<section class="login-service-section">
    <div class="container-fluid">
        <div class="row login-row">
            <div class="col-md-5 left-col hl-178">
                <div class="inner-col">
                    <img src="/assets/images/Ceda-Black.svg" alt="CEDA Logo">
                    <h2 class="left-content">Lorem ipsum is placeholder text commonly</h2>
                    <p class="left-content-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="col-md-7 right-col others micro">
                <div class="inner-col">
                    <img src="/assets/images/firework.svg" alt="firework">
                    <h2 class="form-heading">Welcome to Ceda</h2>
                    <p class="contact-form-sub-heading">You are one click away from archieveing your savings goals!</p>
                    <form action="" class="right-form">
                        <div class="form-group">
                            <label class="form-labels" for="email">Your business name</label>
                            <input type="business_name" class="form-control input-login" id="business_name" placeholder="Enter your business name">
                        </div>
                        <div class="form-group">
                            <label class="form-labels" for="email">Your business email</label>
                            <input type="business_email" class="form-control input-login" id="business_email" placeholder="Enter your business email">
                        </div>
                        <div class="form-group">
                            <label class="form-labels" for="email">Business location</label>
                            <select type="business_location" class="form-control input-login" id="business_location">
                                <option value="">Select country</option>
                            </select>
                        </div>
                        <button class="btn-submit mt-24 p-0 ht-50">Continue</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include 'templates/footer.phtml'; ?>