<section class="hero-title">
    <div class="container">
        <h1 class="page-title">Privacy</h1>
    </div>
</section>
<section class="ceda-content-wrapper">
    <div class="container">
        <div class="content-section">
            <h3 class="content-title">Privacy Policy</h3>
            <p class="content-detail">This privacy policy outlines how we collect and use personal information. It also describes
                how we protect that information from unauthorized access or disclosure. This policy covers Ceda's web pages,
                databases, content, and services related to our products and services. Note that when you use any
                of Ceda's services, you agree to this Privacy Policy and our Terms of Use regardless of how you
                access these services. The Privacy Policy below does not apply to third-party websites or services,
                including those owned or controlled by Ceda merchants. We are not responsible for the privacy policies
                of these websites or services, and we cannot guarantee their compliance with our Privacy Policy.

            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Collection of information</h3>
            <p class="content-detail"> When you register for a Ceda account, use our services, contact us, or our customer
                support team, we receive information from you. You also provide us with means of identification like email
                address, bank details, name, telephone number, and IP address. We may also collect personal information
                from you like your full name(s), identity number, identity card, passport or photographs, bank verification
                number (BVN), NIN, and date of birth. This allows us to verify your identity before we let you access some
                of our services.

                <br>  <br>
                We also record data like conversations between; us and customers and your inclination towards marketing
                materials from us and other third-party clients. We record data from all transactions performed on our
                platform to ensure smooth processes. We also record financial information we receive from you and other
                financial institutions.


            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Use of information</h3>
            <p class="content-detail">We use the information we collect to verify your identity, prevent fraudulent activities,
                unauthorized transactions, and improve how we serve you. We use it to respond to your queries, process transactions,
                and bring you our products, offers, and services. At Ceda, we want to provide the best possible user experience.
                We collect, analyze and utilize the data we collect to improve our web pages and other internal components of our
                operations. We may also collect additional data for specific purposes.

            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Sharing information with other parties</h3>
            <p class="content-detail">We may share your personal information with third parties, service providers, agents,
                suppliers, and subcontractors who supply services to us. Only the third party will have the right to use your
                personal information after we have received your consent. These parties agree to process your information based
                on our instructions. They must also comply with our Privacy Policy and other appropriate confidentiality and
                security measures. We must receive your legal authorization before sharing your information, but we are not
                liable for any breach of privacy or security by any such third party.
                <br>  <br>
                We will not act on your personal information without the consent you provide to us, and you have the right/choice to withdraw
                the consent you gave.
                However, you may not be able to access certain services or all the services Ceda provides.
                <br>  <br>


                Notwithstanding the above, if we receive an Order from a Court or other governmental body having authority
                to issue such orders, then we may, without violating the obligations set forth in this Agreement, disclose
                certain Confidential Information to the extent such disclosure (i) is required by a valid Order of a Court
                or other governmental agency having jurisdiction; (ii) is required by a subpoena or other legal process
                served upon the Receiving Party; or (iii) is otherwise necessary to comply with any applicable law or regulation.


            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Safety of your personal information </h3>
            <p class="content-detail">We have implemented appropriate security precautions to prevent unauthorized access to
                your Personal Information. When transmitting bank account information, such information will be securely
                encrypted for transmission over the Internet. We also only share your personal data with those employees,
                agents, contractors, subcontractors, and other third parties who need it for operations related to your account.
                These parties will only process your personal information when they receive instructions from us.
                <br>  <br>
                We have established processes to deal with any suspected personal data breach and will notify you and applicable
                regulators of such a breach where required by law. We cannot guarantee the absolute security of your Personal
                Information transmitted or stored electronically. Please safeguard your password for your Ceda account, and do
                not share it with anyone else. When we receive instructions using your Ceda account login information, we will
                consider that you have authorized those instructions. You agree to notify us immediately of any unauthorized use
                of your Ceda account or any other security breach.
                <br>  <br>
                We will keep your information for as long as we must to fulfill the purposes for collecting it, including fulfilling
                legal requirements, accounting procedures, and reporting obligations. We reserve the right to refuse to provide our
                Services and terminate your Ceda account if we believe that you have breached these Terms of Service or any other
                agreement with us.


            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Cookies</h3>
            <p class="content-detail">We use cookies to ensure that we give you the best experience on our website.
                Cookies allow us to remember information about your preferences and provide a customized browsing experience.
                They also help us gather information about how you use our site so that we can improve our services. We do not
                share this information with other organizations, except in the case of protecting against fraud or preventing
                potential harm to minors. We use cookies to help you use our website as efficiently as possible. You can disable
                them on our website, but you will not get the best experience using our website. If you do not opt-out of Cookies,
                we will operate under the assumption you consent to the use of Cookies.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Age Limits</h3>
            <p class="content-detail">Our Services are not for persons under the age of eighteen (18). We will not knowingly
                collect Personal Information from children under that age. If you are under eighteen (18), please do not use
                the services and do not provide any personal data to us. Please get in touch with us using the information
                provided in this Privacy Policy if, as a parent or guardian, you learn that your child or ward child has given
                us any information without your permission.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Contact Us</h3>
            <p class="content-detail">Please contact us if you have any questions, concerns, or comments regarding your personal information,
                or this privacy policy. You can reach out to the customer service support available via our 24/7 live chat on the website.
                You can also send an email to <a href="mailto:support@cedamoney.com">support@cedamoney.com</a>

            </p>
        </div>

    </div>
</section>
<?php include 'templates/footer.phtml'; ?>