<section class="login-service-section">
    <div class="container-fluid">
        <div class="row login-row">
            <div class="col-md-5 left-col">
                <div class="inner-col">
                    <img src="/assets/images/Ceda-Black.svg" alt="CEDA Logo">
                    <h2 class="left-content">Lorem ipsum is placeholder text commonly</h2>
                    <p class="left-content-text">Lorem Ipsum is simply dummy text of the printing and typesetting
                        industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                        unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="col-md-7 right-col">
                <div class="inner-col">
                    <h2 class="form-heading">Create a Ceda Account</h2>
                    <form action="" id="reg-form">
                        <div class="col-md-12 input-wrapper">
                            <div class="name-wrapper">
                                <div class="name-col">
                                    <div class="form-group mb-0">
                                        <label class="form-labels" for="first_name">First Name</label>
                                        <input type="text" class="form-control input-login" id="first_name" name="first_name"
                                               placeholder="First Name">
                                    </div>
                                </div>
                                <div class="name-col">
                                    <div class="form-group mb-0">
                                        <label class="form-labels" for="last_name">Last Name</label>
                                        <input type="text" class="form-control input-login" id="last_name" name="last_name"
                                               placeholder="Last Name">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 input-wrapper">

                            <div class="form-group">
                                <label class="form-labels" for="phone">Email Address</label>
                                <input type="text" class="form-control input-login-bellow" id="email" name="email"
                                       placeholder="Enter your Email Address">
                            </div>
                        </div>
                        <div class="col-md-12 input-wrapper">
                            <div class="form-group">
                                <label class="form-labels" for="email">Phone Number</label>
                                <div class="input-group pass-wrapper" id="show_hide_password">
                                    <div class="input-group-addon">
                                        <img src="/assets/images/nigeria-flag.svg" alt="nigeria-flag">
                                    </div>
                                    <p class="mb-0 pl-10 line"> | </p>
                                    <input type="number" class="form-control input-login login-pass pl-10" id="phone_number" name="phone_number"
                                           placeholder="Enter phone number ">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 input-wrapper">
                            <div class="form-group">
                                <label class="form-labels" for="password">Enter Password</label>
                                <input type="password" class="form-control input-login-bellow" id="password" name="password"
                                       placeholder="Min. of 8 characters">
                            </div>
                        </div>
                        <div class="col-md-12 input-wrapper">
                            <div class="form-group">
                                <label class="form-labels" for="email">Confirm Password</label>
                                <input type="password" class="form-control input-login-bellow" id="cpassword" name="cpassword"
                                       placeholder="Min. of 8 characters">
                            </div>
                        </div>
                        <div class="bellow-content-wrapper">
                            <p class="acc-type mb-0">What type of account do you own?</p>
                            <div class="below-content">
                                <div class="type">
                                    <div class="type-name">
                                        <input class="checkbox-type" type="checkbox" name="type_name" id="freelancer" value="freelancer"/>
                                        <p class="type-actual mb-0">Freelancer</p>
                                    </div>
                                    <p class="bellow-text mb-0">I run my business personally and would love to receive<br> payments from any part of
                                        the world using Ceda.</p>
                                </div>
                            </div>
                            <div class="below-content mt-24">

                                <div class="type">
                                    <div class="type-name">
                                        <input class="checkbox-type" type="checkbox" name="type_name" id="microbusiness" value="microbusiness"/>
                                        <p class="type-actual mb-0">MicroBusiness</p>
                                    </div>
                                    <p class="bellow-text mb-0">I own a microbusiness and would love to reach my savings goals with the help of Ceda</p>
                                </div>
                            </div>
                        </div>
                        <button class="btn-submit" onclick="addUser()">Register &nbsp; <img src="/assets/images/register.png" alt=""></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include 'templates/footer.phtml'; ?>

<script>
    function addUser(){
        $.ajax({
            url: '/ajax/signup_user',
            method: 'POST',
            dataType: 'JSON',
            data: {
                first_name: $('#first_name').val(),
                last_name: $('#last_name').val(),
                email: $('#email').val(),
                phone_number: $('#phone_number').val(),
                password: $('#password').val(),
                type: $('#type').val(),
            }
        });
    }
</script>
