<section class="login-service-section">
    <div class="container-fluid">
        <div class="row login-row col-rev-ceda">
            <div class="col-md-5 left-col hl-150">
                <div class="inner-col">
                    <a href="/"> <img src="/assets/images/Ceda-Black.svg" class="sign-img" alt="CEDA Logo"></a>
                    <h2 class="left-content">A new world of financial possibilities is within reach with Ceda.</h2>
                    <p class="left-content-text">Enjoy seamless currency exchange and conduct international transactions with ease.</p>
                </div>
                <img src="/assets/images/sign-up-img.png" class="left-col-img">
            </div>
            <div class="col-md-7 right-col">
                <div class="inner-col">
                    <h2 class="form-heading">Create a Ceda Account</h2>
                    <form action="" id="reg-form">
                        <div class="col-md-12 input-wrapper">
                            <div class="name-wrapper">
                                <!--<div class="name-col">
                                    <div class="form-group mb-0">
                                        <label class="form-labels" for="first_name">First Name</label>
                                        <input type="text" class="form-control input-login" id="first_name" name="first_name" required
                                               placeholder="First Name">
                                    </div>
                                </div>-->
                                <div class="name-col">
                                    <div class="form-group mb-0">
                                        <label class="form-labels" for="name">Name</label>
                                        <input type="text" class="form-control input-login" id="name" name="name"
                                               required
                                               placeholder="Full legal name as written on ID card">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 input-wrapper">

                            <div class="form-group">
                                <label class="form-labels" for="phone">Email Address</label>
                                <input type="text" class="form-control input-login-bellow" id="email" name="email"
                                       required
                                       placeholder="Enter your Email Address">
                            </div>
                        </div>
                        <div class="col-md-12 input-wrapper">
                            <div class="form-group">
                                <label class="form-labels" for="email">Phone Number</label>
                                <div class="input-group pass-wrapper">
                                    <input class="form-control input-login login-pass" type="tel"
                                           id="phone_number" placeholder="Enter phone number" name="phone_number[main]"
                                    />
                                </div>
                                <!--<div class="input-group pass-wrapper" id="show_hide_password">
                                    <div class="input-group-addon">
                                        <img src="/assets/images/nigeria-flag.svg" alt="nigeria-flag">
                                    </div>

                                    <p class="mb-0 pl-10 line"> | </p>
                                    <input type="number" class="form-control input-login login-pass pl-10" id="phone_number" name="phone_number" required
                                           placeholder="Enter phone number ">
                                </div>-->
                            </div>
                        </div>
                        <div class="col-md-12 input-wrapper">
                            <div class="form-group">
                                <label class="form-labels" for="password">Enter Password</label>
                                <input type="password" class="form-control input-login-bellow" id="password"
                                       name="password" required
                                       placeholder="Min. of 8 characters">
                            </div>
                        </div>
                        <div class="col-md-12 input-wrapper">
                            <div class="form-group">
                                <label class="form-labels" for="email">Confirm Password</label>
                                <input type="password" class="form-control input-login-bellow" id="cpassword"
                                       name="cpassword" required
                                       placeholder="Min. of 8 characters">
                            </div>
                        </div>
                        <div class="bellow-content-wrapper hidden">
                            <p class="acc-type mb-0">What type of account do you own?</p>
                            <div class="below-content">
                                <div class="type">
                                    <div class="type-name">
                                        <input class="checkbox-type" type="checkbox" name="type_name" id="individual"
                                               value="individual" onclick="check(this);"/>
                                        <p class="type-actual mb-0">Individual</p>
                                    </div>
                                    <p class="bellow-text mb-0">I run my business personally and would love to
                                        receive<br> payments from any part of
                                        the world using Ceda.</p>
                                </div>
                            </div>
                            <div class="below-content mt-24">

                                <div class="type">
                                    <div class="type-name">
                                        <input class="checkbox-type" type="checkbox" name="type_name" id="microbusiness"
                                               value="microbusiness" onclick="check(this);"/>
                                        <p class="type-actual mb-0">MicroBusiness</p>
                                    </div>
                                    <p class="bellow-text mb-0">I own a microbusiness and would love to reach my savings
                                        goals with the help of Ceda</p>
                                </div>
                            </div>
                        </div>
                        <button class="btn-submit">Create my account &nbsp; <img src="/assets/images/register.png" alt="">
                        </button>
                        <div class="register-redirect">
                            Already have an account? <a href="/login">Login here</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include 'templates/footer.phtml'; ?>

<script>
    let type = "individual"

    function check(input) {
        type = input.value;
        console.log(type)
        let checkboxes = document.getElementsByClassName("checkbox-type");

        // for (let i = 0; i < checkboxes.length; i++) {
        //     //uncheck all
        //     if (checkboxes[i].checked == true) {
        //         checkboxes[i].checked = false;
        //     }
        // }

        // //set checked of clicked object
        // if (input.checked == true) {
        //     input.checked = false;
        // } else {
        //     input.checked = true;
        // }
    }
    var phone_number = window.intlTelInput(document.querySelector("#phone_number"), {
        separateDialCode: true,
        hiddenInput: "full",
        utilsScript: "//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/utils.js",
        onlyCountries: ["ng", "pk", "ph"],
    });
    $('.btn-submit').click(function (e) {
        e.preventDefault();
        let password = $('#password').val();
        let cpassword = $('#cpassword').val();
        if ($('#name').val() == '') {
            $('#snackbar').html('Please enter your name');
            showToast();
            return;
        }
        if ($('#email').val() == '') {
            $('#snackbar').html('Please enter your email');
            showToast();
            return;
        }
        if ($('#phone_number').val() == '') {
            $('#snackbar').html('Please enter your phone number');
            showToast();
            return;
        }
        if ($('#name').val() == '') {
            $('#snackbar').html('Please enter your name');
            showToast();
            return;
        }
        if ($('#password').val() == '') {
            $('#snackbar').html('Please enter password');
            showToast();
            return;
        }
        var full_number = phone_number.getNumber(intlTelInputUtils.numberFormat.E164);
        let countryData = phone_number.getSelectedCountryData()
        console.log(countryData);
        if (password == cpassword) {
            //$(this).html(` <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>`)
            try {
                $.ajax({
                    url: '/ajax/signup_user',
                    method: 'POST',
                    dataType: 'JSON',
                    data: {
                        name: $('#name').val(),
                        email: $('#email').val(),
                        country: countryData.name,
                        ios2: countryData.iso2,
                        dial_code:countryData.dialCode,
                        phone_number: full_number,
                        password: $('#password').val(),
                        type: type,
                    },
                    success: function (data) {
                        // $(this).html(`<p>Register</p> &nbsp; <img src="/assets/images/register.png" alt="">`)
                        if (data.message !== undefined) {
                            $('#snackbar').html(data.message);
                            showToast();
                            setTimeout(function () {
                                window.location.href = "/login";
                            }, 3000)

                        } else {
                            $('#snackbar').html(data.error);
                            showToast();
                        }
                    }
                });
            } catch (e) {
                console.warn(e)
            }

        } else {
            $('#snackbar').html('Passwords don\'t match');
            showToast();
        }
    })

</script>
