
<section class="login-service-section">
    <div class="container-fluid">
        <div class="row login-row col-rev-ceda">
            <div class="col-md-5 left-col hl-150">
                <div class="inner-col">
                    <img src="/assets/images/Ceda-Black.svg" alt="CEDA Logo">
                    <h2 class="left-content">Lorem ipsum is placeholder text commonly</h2>
                    <p class="left-content-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="col-md-7 right-col others">
                <div class="inner-col">
                    <h2 class="form-heading">Reset Password</h2>
                    <p class="contact-form-sub-heading mt-13">Enter your email address below and we will send you a password reset link</p>
                    <form action="" class="right-form">
                        <div class="form-group">
                            <label class="form-labels" for="email">Email Address</label>
                            <input type="email" class="form-control input-login" id="email" placeholder="Enter your email address">
                        </div>
                        <button class="btn-submit mt-24 p-0 ht-50">Register &nbsp; <img src="/assets/images/register.png" alt=""></button>
                        <div class="register-redirect">
                            No account yet? <a href="/register">Register here</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include 'templates/footer.phtml'; ?>