<div class="col md-4 ceda-wrapper">
    <div class="sidebar-wrapper">
        <div class="sidebar-header">
            <img src="/assets/images/ceda-sidebar.svg" alt="">
        </div>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item nav-li">
                <a href="#" class="nav-link selected sidebar-nav" aria-current="page">
                    <img class="nav-icons" src="/assets/images/home<?=($title == 'Dashboard')?'':'-in'?>.svg" alt="home-icon">
                    <span class="<?=($title=="Dashboard")?'sidebar-title-active':'sidebar-title'?>">Home</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="#" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons" src="/assets/images/convert<?=($title == 'Covert To Local Currency')?'':'-in'?>.svg" alt="home-icon">
                    <span class="<?=($title=="Covert To Local Currency")?'sidebar-title-active':'sidebar-title'?>">Convert to Local Currency</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="#" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons" src="/assets/images/dollar<?=($title == 'Sell Digital Products')?'':'-in'?>.svg" alt="home-icon">
                    <span class="<?=($title=="Sell Digital Products")?'sidebar-title-active':'sidebar-title'?>">Sell Digital Products</span>
                    <span class="coming-soon">Coming Soon</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="#" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons" src="/assets/images/setting<?=($title == 'Settings')?'':'-in'?>.svg" alt="home-icon">
                    <span class="<?=($title=="Settings")?'sidebar-title-active':'sidebar-title'?>">Settings</span>
                </a>
            </li>
        </ul>
    </div>
</div>