<div class="col-md-3 ceda-wrapper hide-on">
    <div class="sidebar-wrapper">
        <div class="sidebar-header">
            <a href="/dashboard">
                <img src="/assets/images/ceda-sidebar.svg" alt="">
            </a>
        </div>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item nav-li">
                <a href="/dashboard" class="nav-link  sidebar-nav <?= ($title == "Dashboard") ? 'selected' : '' ?>" aria-current="page">
                    <img class="nav-icons" src="/assets/images/home<?= ($title == 'Dashboard') ? '' : '-in' ?>.svg"
                         alt="home-icon">
                    <span class="<?= ($title == "Dashboard") ? 'sidebar-title-active' : 'sidebar-title' ?>">Home</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/convert-money" class="nav-link  sidebar-nav  <?= ($title == "Convert Money") ? 'selected' : '' ?>" aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/convert<?= ($title == 'Convert Money') ? '' : '-in' ?>.svg"
                         alt="convert-to-local-icon">
                    <span class="<?= ($title == "Convert Money") ? 'sidebar-title-active' : 'sidebar-title' ?>">Convert Money</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="#" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/dollar<?= ($title == 'Sell Digital Products') ? '' : '-in' ?>.svg"
                         alt="sell-digital-products-icon">
                    <span class="<?= ($title == "Sell Digital Products") ? 'sidebar-title-active' : 'sidebar-title' ?>">Intl. Bank Accounts <br> for Salary & Payments</span>
<!--                    <span class="coming-soon">Coming Soon</span>-->
                </a>
            </li>
           <li class="nav-item nav-li">
                <a href="/transaction" class="nav-link  sidebar-nav <?= ($title == "Transaction") ? 'selected' : '' ?>" aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/transaction<?= ($title == 'Transaction') ? '' : '-in' ?>.svg"
                         alt="transactions-icon">
                    <span class="<?= ($title == "Transaction") ? 'sidebar-title-active' : 'sidebar-title' ?>">Transactions</span>

                </a>
            </li>
            <!-- <li class="nav-item nav-li">
                <a href="/get-freelancing-advice" class="nav-link  sidebar-nav" aria-current="page">
                    <img class="nav-icons"
                         src="/assets/images/transaction<?= ($title == 'Get Freelancing Advice') ? '' : '-in' ?>.svg"
                         alt="sell-digital-products-icon">
                    <span class="<?= ($title == "Get Freelancing Advice") ? 'sidebar-title-active' : 'sidebar-title' ?>">Get Freelancing Advice</span>

                </a>
            </li> -->
            <li class="nav-item nav-li">
                <a href="/settings" class="nav-link sidebar-nav <?= ($title == "Settings") ? 'selected' : '' ?>" aria-current="page">
                    <img class="nav-icons" src="/assets/images/setting<?= ($title == 'Settings') ? '' : '-in' ?>.svg"
                         alt="setting-icon">
                    <span class="<?= ($title == "Settings") ? 'sidebar-title-active' : 'sidebar-title' ?>">Settings</span>
                </a>
            </li>
            <li class="nav-item nav-li">
                <a href="/logout" class="nav-link sidebar-nav aria-current="page">
                    <img class="nav-icons" src="/assets/images/logout.svg"
                         alt="setting-icon">
                    <span class="sidebar-title">Log out</span>
                </a>
            </li>
        </ul>
    </div>
</div>