<section class="hero-title">
    <div class="container">
         <h1 class="page-title">Terms Of Use</h1>
    </div>
</section>
<section class="ceda-content-wrapper">
    <div class="container">
        <div class="content-section">
            <h3 class="content-title">Terms of Use</h3>
            <p class="content-detail">These Terms and Conditions create a legally binding contractual
                relationship between you and Brace Network, LLC (Owners of Ceda). Please, read carefully.
                By accessing the Ceda website (the "Site", the "Platform") and using the features, products,
                and services provided by Brace Network, LLC ( the "Company", "we", "us" or "our") through the
                Site, you consent to be bound by these terms. You agree to these Terms of Service below when you
                register for an account with Ceda or use any of our services. This agreement will govern
                every customer’s access and use of Ceda’s website, web pages, mobile applications, and services.
                We enumerate any risks associated with using Ceda and believe that when you use Ceda, you have
                accessed these risks and agree to this agreement.

            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Disclaimer, Liability, and Indemnity</h3>
            <p class="content-detail">At Ceda, we work to make sure that our website, mobile application, and other
                services run smoothly. We ensure they are always available and problem-free, but you use these services
                at your own risk. Our website and services are provided “as is” without any guarantees, expressed or implied.
                We don't guarantee that our website will meet your requirements or be uninterrupted, timely, secure,
                or error-free. Ceda, our website, and any other affiliated companies make no warranties, whether express
                or implied, including those of merchantability or fitness for a particular purpose. Ceda will not be liable
                for any direct or indirect, incidental, punitive, consequential, special, or exemplary damages or any other
                damages, including damages resulting from lost profits, lost revenues, use, data, or goodwill, business
                interruption, or other intangible losses arising out or in connection with the use of our website or services.
                By using our services, you agree to indemnify us and keep us indemnified against any losses (including but
                not limited to legal fees), damages, costs, liabilities, and expenses arising from your use of our services.
                You agree to indemnify and hold Ceda harmless from and against any claims, suits, or proceedings brought
                against Ceda arising out of or in connection with violations by you of intellectual property or other
                rights of a third party. Any provision of this Agreement that is invalid, illegal, or unenforceable shall
                not affect the validity or legality of the remaining provisions of the Agreement.

            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Laws</h3>
            <p class="content-detail">Ceda’s services are provided by Brace Network, LLC, a company duly incorporated
                under the laws of the State of Wyoming, USA. All terms and conditions of this agreement will be governed
                by the laws of the United States of America.

        </div>
        <div class="content-section">
            <h3 class="content-title">Intellectual Property</h3>
            <p class="content-detail">Ceda owns the intellectual property rights and materials
                on our website. All text and materials on the Ceda website and applications and
                other materials and information on the website are subject to the intellectual property rights of Ceda.

            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Identity Verification</h3>
            <p class="content-detail">When you register for a Ceda account, you provide us with means of
                identification like name(s),  email address, and telephone number. You agree for us to use this
                information to verify your identity. If any of these data changes, you should notify us within seven
                (7) days to effect the changes on our end and keep our services seamless. We will not respond to your
                requests if the name(s), email address, and telephone number you contact us with do not match up with
                the contact details we have.

            </p>
        </div>
        <div class="content-section">
            <h3 class="content-title">Software License</h3>
            <p class="content-detail">You agree not to alter, reproduce, adapt, distribute, display, publish, reverse-engineer,
                or translate the Software; you may not disassemble or decompile the Software, and you agree not to re-create
                any source code derived from Ceda’s Software.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Account Security</h3>
            <p class="content-detail">All your account details, especially your passwords, should be guarded safely. You agree to
                protect this information and not disclose this information to anyone for any reason. If you disclose this information,
                Ceda is not liable for any loss or damages.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Age Limits</h3>
            <p class="content-detail">Our Services are not for persons under the age of eighteen (18). We will not knowingly collect Personal
                Information from children under that age. If you are under eighteen (18), please do not use the services and do not provide any
                personal data to us. Please contact us using the information provided in this Privacy Policy if,
                as a parent or guardian, you learn that your child or ward child has given us any information without your permission.
            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Fees</h3>
            <p class="content-detail">You agree to pay Ceda for every service we render. All fees will be clearly enumerated,
                but we have the right to change them. However, if we change our fees, we agree to notify you within 24-48 hours of the change.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Updates to Terms of Service</h3>
            <p class="content-detail">Ceda reserves the right to change, revise or amend these terms at any time.
                We encourage you to check back frequently for updates or changes. The current version of these
                terms will always be on this webpage and will govern our relationship with you. We will also try
                to notify you of changes within 24-48 hours. By continuing to use the Service after the new terms
                take effect, you agree to be legally bound by them.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Termination</h3>
            <p class="content-detail">This Agreement can only be terminated when you close your Ceda account.
                However, we can close your accounts, remove your access to any of our services, and or freeze
                your funds. We can terminate this Agreement if you do not comply with or breach any of its provisions.
                If we believe your account is abusing our services, we may close your account. We reserve the right
                to close your accounts, remove access to any of our services, or freeze your funds if directed by law,
                Card network rules, or your issuing financial institution. We may also close your account if we detect
                fraudulent or suspicious transactions.

            </p>
        </div>

        <div class="content-section">
            <h3 class="content-title">Contact Us</h3>
            <p class="content-detail">Please contact us if you have any questions, concerns, or comments regarding our Terms
                of Use, you can reach out to the customer service support available via our 24/7 live chat on the website.
                You can also send an email to <a href="mailto:support@cedamoney.freshdesk.com">support@cedamoney.freshdesk.com</a>


            </p>
        </div>

    </div>
</section>
<?php include 'templates/footer.phtml'; ?>